/*
 * JS for CRUNCHBASE_companyInfo generated by Appery.io
 *
 */

Appery.getProjectGUID = function() {
    return '10159332-6ca9-4e3e-8d2b-7b3a2ee01b02';
}

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Appery.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Appery.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "CRUNCHBASE_search",
    "location": "CRUNCHBASE_search.html"
}, {
    "name": "CRUNCHBASE_financialOrgInfo",
    "location": "CRUNCHBASE_financialOrgInfo.html"
}, {
    "name": "CRUNCHBASE_milestonesList",
    "location": "CRUNCHBASE_milestonesList.html"
}, {
    "name": "CRUNCHBASE_peopleList",
    "location": "CRUNCHBASE_peopleList.html"
}, {
    "name": "CRUNCHBASE_serviceProviderInfo",
    "location": "CRUNCHBASE_serviceProviderInfo.html"
}, {
    "name": "CRUNCHBASE_officesList",
    "location": "CRUNCHBASE_officesList.html"
}, {
    "name": "CRUNCHBASE_showMap",
    "location": "CRUNCHBASE_showMap.html"
}, {
    "name": "CRUNCHBASE_competitorsList",
    "location": "CRUNCHBASE_competitorsList.html"
}, {
    "name": "CRUNCHBASE_personInfo",
    "location": "CRUNCHBASE_personInfo.html"
}, {
    "name": "CRUNCHBASE_productsList",
    "location": "CRUNCHBASE_productsList.html"
}, {
    "name": "CRUNCHBASE_productInfo",
    "location": "CRUNCHBASE_productInfo.html"
}, {
    "name": "CRUNCHBASE_companyInfo",
    "location": "CRUNCHBASE_companyInfo.html"
}];

CRUNCHBASE_companyInfo_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_home': 'CRUNCHBASE_companyInfo_mobilebutton_home',
        'mobilebutton_back': 'CRUNCHBASE_companyInfo_mobilebutton_back',
        'mobilegrid_nameAndImage': 'CRUNCHBASE_companyInfo_mobilegrid_nameAndImage',
        'mobilegridcell_name': 'CRUNCHBASE_companyInfo_mobilegridcell_name',
        'mobilelink_companyName': 'CRUNCHBASE_companyInfo_mobilelink_companyName',
        'mobilegridcell_image': 'CRUNCHBASE_companyInfo_mobilegridcell_image',
        'mobileimage_company': 'CRUNCHBASE_companyInfo_mobileimage_company',
        'mobilelabel_category': 'CRUNCHBASE_companyInfo_mobilelabel_category',
        'mobilelabel_descriptionCompany': 'CRUNCHBASE_companyInfo_mobilelabel_descriptionCompany',
        'mobilegroupedbuttons_companyInfo': 'CRUNCHBASE_companyInfo_mobilegroupedbuttons_companyInfo',
        'mobilebutton_Overview': 'CRUNCHBASE_companyInfo_mobilebutton_Overview',
        'mobilebutton_Offices': 'CRUNCHBASE_companyInfo_mobilebutton_Offices',
        'mobilebutton_People': 'CRUNCHBASE_companyInfo_mobilebutton_People',
        'mobilebutton_Products': 'CRUNCHBASE_companyInfo_mobilebutton_Products',
        'mobilebutton_Competitors': 'CRUNCHBASE_companyInfo_mobilebutton_Competitors',
        'mobilebutton_Milestones': 'CRUNCHBASE_companyInfo_mobilebutton_Milestones',
        'mobilelabel_overviewText': 'CRUNCHBASE_companyInfo_mobilelabel_overviewText',
        'mobilelabel_noInformationOverview': 'CRUNCHBASE_companyInfo_mobilelabel_noInformationOverview',
        'mobilelabel_foundedYear': 'CRUNCHBASE_companyInfo_mobilelabel_foundedYear',
        'mobilelabel_foundedMonth': 'CRUNCHBASE_companyInfo_mobilelabel_foundedMonth',
        'mobilelabel_foundedDay': 'CRUNCHBASE_companyInfo_mobilelabel_foundedDay',
        'mobilelabel_deadpooledCompanyYear': 'CRUNCHBASE_companyInfo_mobilelabel_deadpooledCompanyYear',
        'mobilelabel_deadpooledCompanyDay': 'CRUNCHBASE_companyInfo_mobilelabel_deadpooledCompanyDay',
        'mobilelabel_deadpooledCompanyMonth': 'CRUNCHBASE_companyInfo_mobilelabel_deadpooledCompanyMonth',
        'mobilelabel_numberOfEmployees': 'CRUNCHBASE_companyInfo_mobilelabel_numberOfEmployees',
        'mobilelabel_overview': 'CRUNCHBASE_companyInfo_mobilelabel_overview',
        'mobilelabel_contactsText': 'CRUNCHBASE_companyInfo_mobilelabel_contactsText',
        'mobilelabel_noInformationContacts': 'CRUNCHBASE_companyInfo_mobilelabel_noInformationContacts',
        'mobilelabel_phoneNumber': 'CRUNCHBASE_companyInfo_mobilelabel_phoneNumber',
        'mobilelabel_email': 'CRUNCHBASE_companyInfo_mobilelabel_email',
        'mobilelink_blog': 'CRUNCHBASE_companyInfo_mobilelink_blog',
        'mobilelink_twitter': 'CRUNCHBASE_companyInfo_mobilelink_twitter',
        'mobilelabel_loadingText': 'CRUNCHBASE_companyInfo_mobilelabel_loadingText',
        'mobilebutton_retry': 'CRUNCHBASE_companyInfo_mobilebutton_retry'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=page] div[data-role=footer]").css("bottom", "-36px");
    }

    if (Appery.getTargetPlatform == "I") {
        $.each(window.n2id, function(name, id) {
            var elApperyRole = $("#" + id).attr("data-role");
            if (elApperyRole != "appery_label" && elApperyRole != "appery_link") {
                var appleDataSelector = "#" + id + "[x-apple-data-detectors], #" + id + " [x-apple-data-detectors]";
                $(appleDataSelector).attr("x-apple-data-detectors", "false");
            }
        });
    }

    Appery.CurrentScreen = 'CRUNCHBASE_companyInfo';

    /*
     * Nonvisual components
     */
    var datasources = [];

    getCompanyInfo = new Appery.DataSource(CRUNCHBASE_getCompany, {
        'onComplete': function(jqXHR, textStatus) {

            $t.refreshScreenFormElements("CRUNCHBASE_companyInfo");
        },
        'onSuccess': function(data) {
            if (!Helper.fromListPage) {
                Helper.saveResponse(data);
            }

            Helper.setLoadingCompanySuccessState();
        },
        'onError': function(jqXHR, textStatus, errorThrown) {
            Helper.setLoadingFailedState('mobilebutton_retry', 'mobilelabel_loadingText');
        },
        'responseMapping': [{
            'PATH': ['image', 'available_sizes', '[0]', '.'],
            'ID': 'mobileimage_company',
            'ATTR': 'src',
            'TRANSFORMATION': function(value, element) {
                return Helper.getImage(value, element);
            }
        }, {
            'PATH': ['name'],
            'ID': 'mobilelink_companyName',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                Helper.setElementVisibility(value, element);
            }
        }, {
            'PATH': ['homepage_url'],
            'ID': 'mobilelink_companyName',
            'ATTR': 'href'
        }, {
            'PATH': ['blog_url'],
            'ID': 'mobilelink_blog',
            'ATTR': 'href',
            'TRANSFORMATION': function(value, element) {
                Helper.setElementVisibility(value, element);
                Helper.setNoInformationState(value, 'mobilelabel_noInformationContacts');
            }
        }, {
            'PATH': ['twitter_username'],
            'ID': 'mobilelink_twitter',
            'ATTR': 'href',
            'TRANSFORMATION': function(value, element) {
                Helper.setElementVisibility(value, element);
                Helper.setNoInformationState(value, 'mobilelabel_noInformationContacts');
                return Helper.getNewValue(value, "http://twitter.com/");
            }
        }, {
            'PATH': ['category_code'],
            'ID': 'mobilelabel_category',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                Helper.setElementVisibility(value, element);
                return Helper.getNewValue(value, 'Category: ');
            }
        }, {
            'PATH': ['number_of_employees'],
            'ID': 'mobilelabel_numberOfEmployees',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                Helper.setElementVisibility(value, element);
                Helper.setNoInformationState(value, 'mobilelabel_noInformationOverview');
                return Helper.getNewValue(value, "Number of employees: ");
            }
        }, {
            'PATH': ['founded_year'],
            'ID': 'mobilelabel_foundedYear',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                Helper.setNoInformationState(value, 'mobilelabel_noInformationOverview');
            }
        }, {
            'PATH': ['founded_month'],
            'ID': 'mobilelabel_foundedMonth',
            'ATTR': '@'
        }, {
            'PATH': ['founded_day'],
            'ID': 'mobilelabel_foundedDay',
            'ATTR': '@'
        }, {
            'PATH': ['deadpooled_year'],
            'ID': 'mobilelabel_deadpooledCompanyYear',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                Helper.setNoInformationState(value, 'mobilelabel_noInformationOverview');
            }
        }, {
            'PATH': ['deadpooled_month'],
            'ID': 'mobilelabel_deadpooledCompanyMonth',
            'ATTR': '@'
        }, {
            'PATH': ['deadpooled_day'],
            'ID': 'mobilelabel_deadpooledCompanyDay',
            'ATTR': '@'
        }, {
            'PATH': ['email_address'],
            'ID': 'mobilelabel_email',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                Helper.setElementVisibility(value, element);
                Helper.setNoInformationState(value, 'mobilelabel_noInformationContacts');
                return Helper.getNewValue(value, "Email: ");
            }
        }, {
            'PATH': ['phone_number'],
            'ID': 'mobilelabel_phoneNumber',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                Helper.setElementVisibility(value, element);
                Helper.setNoInformationState(value, 'mobilelabel_noInformationContacts');
                return Helper.getNewValue(value, "Phone number: ");
            }
        }, {
            'PATH': ['description'],
            'ID': 'mobilelabel_descriptionCompany',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                Helper.setElementVisibility(value, element);
            }
        }, {
            'PATH': ['overview'],
            'ID': 'mobilelabel_overview',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                Helper.setElementVisibility(value, element);
                Helper.setNoInformationState(value, 'mobilelabel_noInformationOverview');
            }
        }],
        'requestMapping': [{
            'PATH': ['api_key'],
            'TYPE': 'STRING',
            'ATTR': '{api_key}'
        }, {
            'PATH': ['query'],
            'TYPE': 'STRING',
            'ID': '___local_storage___',
            'ATTR': 'selectedPermalink'
        }, {
            'PATH': ['appery-proxy-url'],
            'HEADER': true,
            'ATTR': 'http://api.crunchbase.com/v/1/company/{query}.js'
        }, {
            'PATH': ['appery-transformation'],
            'HEADER': true,
            'ATTR': 'checkTunnel'
        }, {
            'PATH': ['appery-key'],
            'HEADER': true,
            'ATTR': '1390718929478'
        }, {
            'PATH': ['appery-rest'],
            'HEADER': true,
            'ATTR': '2585836'
        }]
    });

    datasources.push(getCompanyInfo);

    /*
     * Events and handlers
     */

    // Before Show
    CRUNCHBASE_companyInfo_beforeshow = function() {
        Appery.CurrentScreen = "CRUNCHBASE_companyInfo";
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }

    // On Load
    screen_A5D8_onLoad = CRUNCHBASE_companyInfo_onLoad = function() {
        screen_A5D8_elementsExtraJS();
        Helper.loadCompanyPage();;
        localStorage.setItem('currentEntity', 'company');

        // TODO fire device events only if necessary (with JS logic)
        CRUNCHBASE_companyInfo_deviceEvents();
        CRUNCHBASE_companyInfo_windowEvents();
        screen_A5D8_elementsEvents();
    }

    // screen window events
    screen_A5D8_windowEvents = CRUNCHBASE_companyInfo_windowEvents = function() {

        $('#CRUNCHBASE_companyInfo').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    }

    // device events
    CRUNCHBASE_companyInfo_deviceEvents = function() {

        document.addEventListener("deviceready", function() {

        });
    }

    // screen elements extra js
    screen_A5D8_elementsExtraJS = CRUNCHBASE_companyInfo_elementsExtraJS = function() {
        // screen (CRUNCHBASE_companyInfo) extra code

    }

    // screen elements handler
    screen_A5D8_elementsEvents = CRUNCHBASE_companyInfo_elementsEvents = function() {

        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });

        $('#CRUNCHBASE_companyInfo_mobileheader [name="mobilebutton_home"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.goHome();

                }
            },
        });
        $('#CRUNCHBASE_companyInfo_mobileheader [name="mobilebutton_back"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.goBack('CRUNCHBASE_companyInfo');

                }
            },
        });

        $('#CRUNCHBASE_companyInfo_mobilecontainer [name="mobilebutton_Overview"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.navigateToNextListPage('CRUNCHBASE_companyInfo');;

                }
            },
        });
        $('#CRUNCHBASE_companyInfo_mobilecontainer [name="mobilebutton_Offices"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.navigateToNextListPage('CRUNCHBASE_officesList');;

                }
            },
        });
        $('#CRUNCHBASE_companyInfo_mobilecontainer [name="mobilebutton_People"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.navigateToNextListPage('CRUNCHBASE_peopleList');;

                }
            },
        });
        $('#CRUNCHBASE_companyInfo_mobilecontainer [name="mobilebutton_Products"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.navigateToNextListPage('CRUNCHBASE_productsList');;

                }
            },
        });
        $('#CRUNCHBASE_companyInfo_mobilecontainer [name="mobilebutton_Competitors"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.navigateToNextListPage('CRUNCHBASE_competitorsList');;

                }
            },
        });
        $('#CRUNCHBASE_companyInfo_mobilecontainer [name="mobilebutton_Milestones"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.navigateToNextListPage('CRUNCHBASE_milestonesList');

                }
            },
        });

        $('#CRUNCHBASE_companyInfo_mobilecontainer [name="mobilebutton_retry"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.setLoadingState('mobilebutton_retry', 'mobilelabel_loadingText');
                    getCompanyInfo.execute({});

                }
            },
        });

    }

    $("#CRUNCHBASE_companyInfo").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        CRUNCHBASE_companyInfo_beforeshow();
    });

    if (runBeforeShow) {
        CRUNCHBASE_companyInfo_beforeshow();
    } else {
        CRUNCHBASE_companyInfo_onLoad();
    }

}

$("#CRUNCHBASE_companyInfo").die("pageinit").live("pageinit", function(event, ui) {
    Appery.processSelectMenu($(this));
    CRUNCHBASE_companyInfo_js();
});