/*
 * JS for CRUNCHBASE_competitorsList generated by Appery.io
 *
 */

Appery.getProjectGUID = function() {
    return '10159332-6ca9-4e3e-8d2b-7b3a2ee01b02';
}

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Appery.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Appery.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "CRUNCHBASE_search",
    "location": "CRUNCHBASE_search.html"
}, {
    "name": "CRUNCHBASE_financialOrgInfo",
    "location": "CRUNCHBASE_financialOrgInfo.html"
}, {
    "name": "CRUNCHBASE_milestonesList",
    "location": "CRUNCHBASE_milestonesList.html"
}, {
    "name": "CRUNCHBASE_peopleList",
    "location": "CRUNCHBASE_peopleList.html"
}, {
    "name": "CRUNCHBASE_serviceProviderInfo",
    "location": "CRUNCHBASE_serviceProviderInfo.html"
}, {
    "name": "CRUNCHBASE_officesList",
    "location": "CRUNCHBASE_officesList.html"
}, {
    "name": "CRUNCHBASE_showMap",
    "location": "CRUNCHBASE_showMap.html"
}, {
    "name": "CRUNCHBASE_competitorsList",
    "location": "CRUNCHBASE_competitorsList.html"
}, {
    "name": "CRUNCHBASE_personInfo",
    "location": "CRUNCHBASE_personInfo.html"
}, {
    "name": "CRUNCHBASE_productsList",
    "location": "CRUNCHBASE_productsList.html"
}, {
    "name": "CRUNCHBASE_productInfo",
    "location": "CRUNCHBASE_productInfo.html"
}, {
    "name": "CRUNCHBASE_companyInfo",
    "location": "CRUNCHBASE_companyInfo.html"
}];

CRUNCHBASE_competitorsList_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_home': 'CRUNCHBASE_competitorsList_mobilebutton_home',
        'mobilebutton_back': 'CRUNCHBASE_competitorsList_mobilebutton_back',
        'mobilegrid_nameAndImage': 'CRUNCHBASE_competitorsList_mobilegrid_nameAndImage',
        'mobilegridcell_name': 'CRUNCHBASE_competitorsList_mobilegridcell_name',
        'mobilelink_companyName': 'CRUNCHBASE_competitorsList_mobilelink_companyName',
        'mobilegridcell_image': 'CRUNCHBASE_competitorsList_mobilegridcell_image',
        'mobileimage_company': 'CRUNCHBASE_competitorsList_mobileimage_company',
        'mobilelabel_category': 'CRUNCHBASE_competitorsList_mobilelabel_category',
        'mobilelabel_descriptionCompany': 'CRUNCHBASE_competitorsList_mobilelabel_descriptionCompany',
        'mobilegroupedbuttons_companyInfo': 'CRUNCHBASE_competitorsList_mobilegroupedbuttons_companyInfo',
        'mobilebutton_Overview': 'CRUNCHBASE_competitorsList_mobilebutton_Overview',
        'mobilebutton_Offices': 'CRUNCHBASE_competitorsList_mobilebutton_Offices',
        'mobilebutton_People': 'CRUNCHBASE_competitorsList_mobilebutton_People',
        'mobilebutton_Products': 'CRUNCHBASE_competitorsList_mobilebutton_Products',
        'mobilebutton_Competitors': 'CRUNCHBASE_competitorsList_mobilebutton_Competitors',
        'mobilebutton_Milestones': 'CRUNCHBASE_competitorsList_mobilebutton_Milestones',
        'mobilelabel_competitors': 'CRUNCHBASE_competitorsList_mobilelabel_competitors',
        'mobilelabel_noInformationCompetitors': 'CRUNCHBASE_competitorsList_mobilelabel_noInformationCompetitors',
        'mobilelist_competitors': 'CRUNCHBASE_competitorsList_mobilelist_competitors',
        'mobilelistitem_competitors': 'CRUNCHBASE_competitorsList_mobilelistitem_competitors',
        'mobilelabel_competitorName': 'CRUNCHBASE_competitorsList_mobilelabel_competitorName',
        'mobilelabel_competitorParmalink': 'CRUNCHBASE_competitorsList_mobilelabel_competitorParmalink',
        'mobilelistitembutton_11': 'CRUNCHBASE_competitorsList_mobilelistitembutton_11'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=page] div[data-role=footer]").css("bottom", "-36px");
    }

    if (Appery.getTargetPlatform == "I") {
        $.each(window.n2id, function(name, id) {
            var elApperyRole = $("#" + id).attr("data-role");
            if (elApperyRole != "appery_label" && elApperyRole != "appery_link") {
                var appleDataSelector = "#" + id + "[x-apple-data-detectors], #" + id + " [x-apple-data-detectors]";
                $(appleDataSelector).attr("x-apple-data-detectors", "false");
            }
        });
    }

    Appery.CurrentScreen = 'CRUNCHBASE_competitorsList';

    /*
     * Nonvisual components
     */
    var datasources = [];

    getCompanyCompetitors = new Appery.DataSource(CRUNCHBASE_getCompany, {
        'onComplete': function(jqXHR, textStatus) {

            $t.refreshScreenFormElements("CRUNCHBASE_competitorsList");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [{
            'PATH': ['image', 'available_sizes', '[0]', '.'],
            'ID': 'mobileimage_company',
            'ATTR': 'src',
            'TRANSFORMATION': function(value, element) {
                return Helper.getImage(value, element);
            }
        }, {
            'PATH': ['competitions'],
            'ID': 'mobilelistitem_competitors',
            'TRANSFORMATION': function(value, element) {
                Helper.setCompetitorListItemVisibility(value, element);
            },
            'SET': [{
                'PATH': ['competitor', 'name'],
                'ID': 'mobilelabel_competitorName',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    Helper.setNoInformationVisibility(value, 'mobilelabel_noInformationCompetitors');
                }
            }, {
                'PATH': ['competitor', 'permalink'],
                'ID': 'mobilelabel_competitorParmalink',
                'ATTR': '@'
            }]
        }, {
            'PATH': ['name'],
            'ID': 'mobilelink_companyName',
            'ATTR': '@'
        }, {
            'PATH': ['homepage_url'],
            'ID': 'mobilelink_companyName',
            'ATTR': 'href'
        }, {
            'PATH': ['category_code'],
            'ID': 'mobilelabel_category',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                Helper.setElementVisibility(value, element);
                return Helper.getNewValue(value, 'Category: ');
            }
        }, {
            'PATH': ['description'],
            'ID': 'mobilelabel_descriptionCompany',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                Helper.setElementVisibility(value, element);
            }
        }],
        'requestMapping': [{
            'PATH': ['api_key'],
            'TYPE': 'STRING',
            'ATTR': '{api_key}'
        }, {
            'PATH': ['query'],
            'TYPE': 'STRING',
            'ID': '___local_storage___',
            'ATTR': 'selectedPermalink'
        }, {
            'PATH': ['appery-proxy-url'],
            'HEADER': true,
            'ATTR': 'http://api.crunchbase.com/v/1/company/{query}.js'
        }, {
            'PATH': ['appery-transformation'],
            'HEADER': true,
            'ATTR': 'checkTunnel'
        }, {
            'PATH': ['appery-key'],
            'HEADER': true,
            'ATTR': '1390718929094'
        }, {
            'PATH': ['appery-rest'],
            'HEADER': true,
            'ATTR': '2585836'
        }]
    });

    datasources.push(getCompanyCompetitors);

    /*
     * Events and handlers
     */

    // Before Show
    CRUNCHBASE_competitorsList_beforeshow = function() {
        Appery.CurrentScreen = "CRUNCHBASE_competitorsList";
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }

    // On Load
    screen_8369_onLoad = CRUNCHBASE_competitorsList_onLoad = function() {
        screen_8369_elementsExtraJS();
        getCompanyCompetitors.updateComponents(Helper.getJsonObject());

        // TODO fire device events only if necessary (with JS logic)
        CRUNCHBASE_competitorsList_deviceEvents();
        CRUNCHBASE_competitorsList_windowEvents();
        screen_8369_elementsEvents();
    }

    // screen window events
    screen_8369_windowEvents = CRUNCHBASE_competitorsList_windowEvents = function() {

        $('#CRUNCHBASE_competitorsList').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    }

    // device events
    CRUNCHBASE_competitorsList_deviceEvents = function() {

        document.addEventListener("deviceready", function() {

        });
    }

    // screen elements extra js
    screen_8369_elementsExtraJS = CRUNCHBASE_competitorsList_elementsExtraJS = function() {
        // screen (CRUNCHBASE_competitorsList) extra code

        /* mobilelist_competitors */

        listView = $("#CRUNCHBASE_competitorsList_mobilelist_competitors");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#CRUNCHBASE_competitorsList_mobilelist_competitors .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_competitors */

    }

    // screen elements handler
    screen_8369_elementsEvents = CRUNCHBASE_competitorsList_elementsEvents = function() {

        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });

        $('#CRUNCHBASE_competitorsList_mobileheader [name="mobilebutton_home"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.goHome();

                }
            },
        });
        $('#CRUNCHBASE_competitorsList_mobileheader [name="mobilebutton_back"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.goBack('CRUNCHBASE_competitorsList');

                }
            },
        });

        $('#CRUNCHBASE_competitorsList_mobilecontainer [name="mobilebutton_Overview"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.navigateToNextListPage('CRUNCHBASE_companyInfo');;

                }
            },
        });
        $('#CRUNCHBASE_competitorsList_mobilecontainer [name="mobilebutton_Offices"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.navigateToNextListPage('CRUNCHBASE_officesList');;

                }
            },
        });
        $('#CRUNCHBASE_competitorsList_mobilecontainer [name="mobilebutton_People"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.navigateToNextListPage('CRUNCHBASE_peopleList');;

                }
            },
        });
        $('#CRUNCHBASE_competitorsList_mobilecontainer [name="mobilebutton_Products"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.navigateToNextListPage('CRUNCHBASE_productsList');;

                }
            },
        });
        $('#CRUNCHBASE_competitorsList_mobilecontainer [name="mobilebutton_Competitors"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.navigateToNextListPage('CRUNCHBASE_competitorsList');;

                }
            },
        });
        $('#CRUNCHBASE_competitorsList_mobilecontainer [name="mobilebutton_Milestones"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.navigateToNextListPage('CRUNCHBASE_milestonesList');

                }
            },
        });

        $('#CRUNCHBASE_competitorsList_mobilecontainer [name="mobilelistitem_competitors"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Pages.push('CRUNCHBASE_companyInfo', localStorage.getItem('selectedPermalink'));
                    setVar_('selectedPermalink', 'CRUNCHBASE_competitorsList_mobilelabel_competitorParmalink', 'text', '', this);
                    Helper.navigateToNextPage('company', 'CRUNCHBASE_competitorsList');

                }
            },
        });

    }

    $("#CRUNCHBASE_competitorsList").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        CRUNCHBASE_competitorsList_beforeshow();
    });

    if (runBeforeShow) {
        CRUNCHBASE_competitorsList_beforeshow();
    } else {
        CRUNCHBASE_competitorsList_onLoad();
    }

}

$("#CRUNCHBASE_competitorsList").die("pageinit").live("pageinit", function(event, ui) {
    Appery.processSelectMenu($(this));
    CRUNCHBASE_competitorsList_js();
});