/*
 * JS for CRUNCHBASE_serviceProviderInfo generated by Appery.io
 *
 */

Appery.getProjectGUID = function() {
    return '10159332-6ca9-4e3e-8d2b-7b3a2ee01b02';
}

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Appery.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Appery.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "CRUNCHBASE_search",
    "location": "CRUNCHBASE_search.html"
}, {
    "name": "CRUNCHBASE_financialOrgInfo",
    "location": "CRUNCHBASE_financialOrgInfo.html"
}, {
    "name": "CRUNCHBASE_milestonesList",
    "location": "CRUNCHBASE_milestonesList.html"
}, {
    "name": "CRUNCHBASE_peopleList",
    "location": "CRUNCHBASE_peopleList.html"
}, {
    "name": "CRUNCHBASE_serviceProviderInfo",
    "location": "CRUNCHBASE_serviceProviderInfo.html"
}, {
    "name": "CRUNCHBASE_officesList",
    "location": "CRUNCHBASE_officesList.html"
}, {
    "name": "CRUNCHBASE_showMap",
    "location": "CRUNCHBASE_showMap.html"
}, {
    "name": "CRUNCHBASE_competitorsList",
    "location": "CRUNCHBASE_competitorsList.html"
}, {
    "name": "CRUNCHBASE_personInfo",
    "location": "CRUNCHBASE_personInfo.html"
}, {
    "name": "CRUNCHBASE_productsList",
    "location": "CRUNCHBASE_productsList.html"
}, {
    "name": "CRUNCHBASE_productInfo",
    "location": "CRUNCHBASE_productInfo.html"
}, {
    "name": "CRUNCHBASE_companyInfo",
    "location": "CRUNCHBASE_companyInfo.html"
}];

CRUNCHBASE_serviceProviderInfo_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_back': 'CRUNCHBASE_serviceProviderInfo_mobilebutton_back',
        'mobilebutton_home': 'CRUNCHBASE_serviceProviderInfo_mobilebutton_home',
        'mobilegrid_nameAndImage': 'CRUNCHBASE_serviceProviderInfo_mobilegrid_nameAndImage',
        'mobilegridcell_name': 'CRUNCHBASE_serviceProviderInfo_mobilegridcell_name',
        'mobilelink_name': 'CRUNCHBASE_serviceProviderInfo_mobilelink_name',
        'mobilegridcell_image': 'CRUNCHBASE_serviceProviderInfo_mobilegridcell_image',
        'mobileimage_serviceProvider': 'CRUNCHBASE_serviceProviderInfo_mobileimage_serviceProvider',
        'mobilelabel_permalink': 'CRUNCHBASE_serviceProviderInfo_mobilelabel_permalink',
        'mobilecollapsibleset_serviceProvInfo': 'CRUNCHBASE_serviceProviderInfo_mobilecollapsibleset_serviceProvInfo',
        'mobilecollapsblock_overview': 'CRUNCHBASE_serviceProviderInfo_mobilecollapsblock_overview',
        'mobilecollapsblockheader_overview': 'CRUNCHBASE_serviceProviderInfo_mobilecollapsblockheader_overview',
        'mobilecollapsblockcontent_overview': 'CRUNCHBASE_serviceProviderInfo_mobilecollapsblockcontent_overview',
        'mobilelabel_overviewText': 'CRUNCHBASE_serviceProviderInfo_mobilelabel_overviewText',
        'mobilelabel_noInformationOverview': 'CRUNCHBASE_serviceProviderInfo_mobilelabel_noInformationOverview',
        'mobilelabel_overview': 'CRUNCHBASE_serviceProviderInfo_mobilelabel_overview',
        'mobilelabel_contactsText': 'CRUNCHBASE_serviceProviderInfo_mobilelabel_contactsText',
        'mobilelabel_noInformationContacts': 'CRUNCHBASE_serviceProviderInfo_mobilelabel_noInformationContacts',
        'mobilelabel_phoneNumber': 'CRUNCHBASE_serviceProviderInfo_mobilelabel_phoneNumber',
        'mobilelabel_emailAddress': 'CRUNCHBASE_serviceProviderInfo_mobilelabel_emailAddress',
        'mobilecollapsblock_providerships': 'CRUNCHBASE_serviceProviderInfo_mobilecollapsblock_providerships',
        'mobilecollapsblockheader_providerships': 'CRUNCHBASE_serviceProviderInfo_mobilecollapsblockheader_providerships',
        'mobilecollapsblockcontent_providerships': 'CRUNCHBASE_serviceProviderInfo_mobilecollapsblockcontent_providerships',
        'mobilelabel_noInformationProviderships': 'CRUNCHBASE_serviceProviderInfo_mobilelabel_noInformationProviderships',
        'mobilelist_providerships': 'CRUNCHBASE_serviceProviderInfo_mobilelist_providerships',
        'mobilelistitem_firm': 'CRUNCHBASE_serviceProviderInfo_mobilelistitem_firm',
        'mobilelistitembutton_23': 'CRUNCHBASE_serviceProviderInfo_mobilelistitembutton_23',
        'mobilelabel_titleProviderships': 'CRUNCHBASE_serviceProviderInfo_mobilelabel_titleProviderships',
        'mobilelabel_isPast': 'CRUNCHBASE_serviceProviderInfo_mobilelabel_isPast',
        'mobilelabel_firmName': 'CRUNCHBASE_serviceProviderInfo_mobilelabel_firmName',
        'mobilelabel_firmPermalink': 'CRUNCHBASE_serviceProviderInfo_mobilelabel_firmPermalink',
        'mobilelabel_typeOfEntity': 'CRUNCHBASE_serviceProviderInfo_mobilelabel_typeOfEntity',
        'mobilelabel_loadingText': 'CRUNCHBASE_serviceProviderInfo_mobilelabel_loadingText',
        'mobilebutton_retry': 'CRUNCHBASE_serviceProviderInfo_mobilebutton_retry'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=page] div[data-role=footer]").css("bottom", "-36px");
    }

    if (Appery.getTargetPlatform == "I") {
        $.each(window.n2id, function(name, id) {
            var elApperyRole = $("#" + id).attr("data-role");
            if (elApperyRole != "appery_label" && elApperyRole != "appery_link") {
                var appleDataSelector = "#" + id + "[x-apple-data-detectors], #" + id + " [x-apple-data-detectors]";
                $(appleDataSelector).attr("x-apple-data-detectors", "false");
            }
        });
    }

    Appery.CurrentScreen = 'CRUNCHBASE_serviceProviderInfo';

    /*
     * Nonvisual components
     */
    var datasources = [];

    getServiceProviderInfo = new Appery.DataSource(CRUNCHBASE_getServiceProvider, {
        'onComplete': function(jqXHR, textStatus) {

            $t.refreshScreenFormElements("CRUNCHBASE_serviceProviderInfo");
        },
        'onSuccess': function(data) {
            Helper.setLoadingServiceProvidarsSuccessState();
        },
        'onError': function(jqXHR, textStatus, errorThrown) {
            Helper.setLoadingFailedState('mobilebutton_retry', 'mobilelabel_loadingText');
        },
        'responseMapping': [{
            'PATH': ['image', 'available_sizes', '[0]', '.'],
            'ID': 'mobileimage_serviceProvider',
            'ATTR': 'src',
            'TRANSFORMATION': function(value, element) {
                return Helper.getImage(value, element);
            }
        }, {
            'PATH': ['providerships'],
            'ID': 'mobilelistitem_firm',
            'SET': [{
                'PATH': ['firm', 'name'],
                'ID': 'mobilelabel_firmName',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    Helper.setNoInformationVisibility(value, 'mobilelabel_noInformationProviderships');
                }
            }, {
                'PATH': ['firm', 'permalink'],
                'ID': 'mobilelabel_firmPermalink',
                'ATTR': '@'
            }, {
                'PATH': ['firm', 'type_of_entity'],
                'ID': 'mobilelabel_typeOfEntity',
                'ATTR': '@'
            }, {
                'PATH': ['title'],
                'ID': 'mobilelabel_titleProviderships',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    Helper.setNoInformationVisibility(value, 'mobilelabel_noInformationProviderships');
                }
            }, {
                'PATH': ['is_past'],
                'ID': 'mobilelabel_isPast',
                'ATTR': 'visible'
            }]
        }, {
            'PATH': ['name'],
            'ID': 'mobilelink_name',
            'ATTR': '@'
        }, {
            'PATH': ['permalink'],
            'ID': 'mobilelabel_permalink',
            'ATTR': '@'
        }, {
            'PATH': ['homepage_url'],
            'ID': 'mobilelink_name',
            'ATTR': 'href'
        }, {
            'PATH': ['phone_number'],
            'ID': 'mobilelabel_phoneNumber',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                Helper.setElementVisibility(value, element);
                Helper.setNoInformationState(value, 'mobilelabel_noInformationContacts');
                return Helper.getNewValue(value, "Phone number: ");
            }
        }, {
            'PATH': ['email_address'],
            'ID': 'mobilelabel_emailAddress',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                Helper.setElementVisibility(value, element);
                Helper.setNoInformationState(value, 'mobilelabel_noInformationContacts');
                return Helper.getNewValue(value, "Email: ");
            }
        }, {
            'PATH': ['overview'],
            'ID': 'mobilelabel_overview',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                Helper.setElementVisibility(value, element);
                Helper.setNoInformationState(value, 'mobilelabel_noInformationOverview');
            }
        }],
        'requestMapping': [{
            'PATH': ['api_key'],
            'TYPE': 'STRING',
            'ATTR': '{api_key}'
        }, {
            'PATH': ['query'],
            'TYPE': 'STRING',
            'ID': '___local_storage___',
            'ATTR': 'selectedPermalink'
        }, {
            'PATH': ['appery-proxy-url'],
            'HEADER': true,
            'ATTR': 'http://api.crunchbase.com/v/1/service-provider/{query}.js'
        }, {
            'PATH': ['appery-transformation'],
            'HEADER': true,
            'ATTR': 'checkTunnel'
        }, {
            'PATH': ['appery-key'],
            'HEADER': true,
            'ATTR': '1390718929017'
        }, {
            'PATH': ['appery-rest'],
            'HEADER': true,
            'ATTR': '2585834'
        }]
    });

    datasources.push(getServiceProviderInfo);

    /*
     * Events and handlers
     */

    // Before Show
    CRUNCHBASE_serviceProviderInfo_beforeshow = function() {
        Appery.CurrentScreen = "CRUNCHBASE_serviceProviderInfo";
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }

    // On Load
    screen_A7CB_onLoad = CRUNCHBASE_serviceProviderInfo_onLoad = function() {
        screen_A7CB_elementsExtraJS();
        Helper.setServiceProvaderInfoInvisibility();
        Helper.setLoadingState('mobilebutton_retry', 'mobilelabel_loadingText');
        getServiceProviderInfo.execute({});
        localStorage.setItem('currentEntity', 'service-provider');

        // TODO fire device events only if necessary (with JS logic)
        CRUNCHBASE_serviceProviderInfo_deviceEvents();
        CRUNCHBASE_serviceProviderInfo_windowEvents();
        screen_A7CB_elementsEvents();
    }

    // screen window events
    screen_A7CB_windowEvents = CRUNCHBASE_serviceProviderInfo_windowEvents = function() {

        $('#CRUNCHBASE_serviceProviderInfo').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    }

    // device events
    CRUNCHBASE_serviceProviderInfo_deviceEvents = function() {

        document.addEventListener("deviceready", function() {

        });
    }

    // screen elements extra js
    screen_A7CB_elementsExtraJS = CRUNCHBASE_serviceProviderInfo_elementsExtraJS = function() {
        // screen (CRUNCHBASE_serviceProviderInfo) extra code

        /* mobilecollapsblock_overview */

        $("#CRUNCHBASE_serviceProviderInfo_mobilecollapsblock_overview .ui-collapsible-heading-toggle").attr("tabindex", "1");

        /* mobilecollapsblock_providerships */

        $("#CRUNCHBASE_serviceProviderInfo_mobilecollapsblock_providerships .ui-collapsible-heading-toggle").attr("tabindex", "2");

        /* mobilelist_providerships */

        listView = $("#CRUNCHBASE_serviceProviderInfo_mobilelist_providerships");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#CRUNCHBASE_serviceProviderInfo_mobilelist_providerships .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_firm */

    }

    // screen elements handler
    screen_A7CB_elementsEvents = CRUNCHBASE_serviceProviderInfo_elementsEvents = function() {

        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });

        $('#CRUNCHBASE_serviceProviderInfo_mobileheader [name="mobilebutton_back"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.goBack('CRUNCHBASE_serviceProviderInfo');

                }
            },
        });
        $('#CRUNCHBASE_serviceProviderInfo_mobileheader [name="mobilebutton_home"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.goHome();

                }
            },
        });

        $('#CRUNCHBASE_serviceProviderInfo_mobilecontainer [name="mobilelistitem_firm"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Pages.push('CRUNCHBASE_serviceProviderInfo', localStorage.getItem('selectedPermalink'));
                    setVar_('selectedPermalink', 'CRUNCHBASE_serviceProviderInfo_mobilelabel_firmPermalink', 'text', '', this);
                    setVar_('currentEntity', 'CRUNCHBASE_serviceProviderInfo_mobilelabel_typeOfEntity', 'text', '', this);
                    Helper.navigateToNextPage(localStorage.getItem('currentEntity'), 'CRUNCHBASE_serviceProviderInfo');

                }
            },
        });

        $('#CRUNCHBASE_serviceProviderInfo_mobilecontainer [name="mobilebutton_retry"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.setLoadingState('mobilebutton_retry', 'mobilelabel_loadingText');
                    getServiceProviderInfo.execute({});

                }
            },
        });

    }

    $("#CRUNCHBASE_serviceProviderInfo").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        CRUNCHBASE_serviceProviderInfo_beforeshow();
    });

    if (runBeforeShow) {
        CRUNCHBASE_serviceProviderInfo_beforeshow();
    } else {
        CRUNCHBASE_serviceProviderInfo_onLoad();
    }

}

$("#CRUNCHBASE_serviceProviderInfo").die("pageinit").live("pageinit", function(event, ui) {
    Appery.processSelectMenu($(this));
    CRUNCHBASE_serviceProviderInfo_js();
});