/*
 * JS for CRUNCHBASE_showMap generated by Appery.io
 *
 */

Appery.getProjectGUID = function() {
    return '10159332-6ca9-4e3e-8d2b-7b3a2ee01b02';
}

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Appery.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Appery.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "CRUNCHBASE_search",
    "location": "CRUNCHBASE_search.html"
}, {
    "name": "CRUNCHBASE_financialOrgInfo",
    "location": "CRUNCHBASE_financialOrgInfo.html"
}, {
    "name": "CRUNCHBASE_milestonesList",
    "location": "CRUNCHBASE_milestonesList.html"
}, {
    "name": "CRUNCHBASE_peopleList",
    "location": "CRUNCHBASE_peopleList.html"
}, {
    "name": "CRUNCHBASE_serviceProviderInfo",
    "location": "CRUNCHBASE_serviceProviderInfo.html"
}, {
    "name": "CRUNCHBASE_officesList",
    "location": "CRUNCHBASE_officesList.html"
}, {
    "name": "CRUNCHBASE_showMap",
    "location": "CRUNCHBASE_showMap.html"
}, {
    "name": "CRUNCHBASE_competitorsList",
    "location": "CRUNCHBASE_competitorsList.html"
}, {
    "name": "CRUNCHBASE_personInfo",
    "location": "CRUNCHBASE_personInfo.html"
}, {
    "name": "CRUNCHBASE_productsList",
    "location": "CRUNCHBASE_productsList.html"
}, {
    "name": "CRUNCHBASE_productInfo",
    "location": "CRUNCHBASE_productInfo.html"
}, {
    "name": "CRUNCHBASE_companyInfo",
    "location": "CRUNCHBASE_companyInfo.html"
}];

CRUNCHBASE_showMap_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'googlemap_officeLocation': 'CRUNCHBASE_showMap_googlemap_officeLocation',
        'marker_2': 'CRUNCHBASE_showMap_marker_2',
        'mobilelabel_noCoordinates': 'CRUNCHBASE_showMap_mobilelabel_noCoordinates'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=page] div[data-role=footer]").css("bottom", "-36px");
    }

    if (Appery.getTargetPlatform == "I") {
        $.each(window.n2id, function(name, id) {
            var elApperyRole = $("#" + id).attr("data-role");
            if (elApperyRole != "appery_label" && elApperyRole != "appery_link") {
                var appleDataSelector = "#" + id + "[x-apple-data-detectors], #" + id + " [x-apple-data-detectors]";
                $(appleDataSelector).attr("x-apple-data-detectors", "false");
            }
        });
    }

    Appery.CurrentScreen = 'CRUNCHBASE_showMap';

    /*
     * Nonvisual components
     */
    var datasources = [];

    /*
     * Events and handlers
     */

    // Before Show
    CRUNCHBASE_showMap_beforeshow = function() {
        Appery.CurrentScreen = "CRUNCHBASE_showMap";
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }

    // On Load
    screen_B551_onLoad = CRUNCHBASE_showMap_onLoad = function() {
        screen_B551_elementsExtraJS();
        Helper.setMap();
        $(window).bind("resize", Helper.resizeMap);

        // TODO fire device events only if necessary (with JS logic)
        CRUNCHBASE_showMap_deviceEvents();
        CRUNCHBASE_showMap_windowEvents();
        screen_B551_elementsEvents();
    }

    // screen window events
    screen_B551_windowEvents = CRUNCHBASE_showMap_windowEvents = function() {

        $('#CRUNCHBASE_showMap').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
        $('#CRUNCHBASE_showMap').bind({
            pagehide: function() {
                $(window).unbind("resize", Helper.resizeMap);
            },
        });

    }

    // device events
    CRUNCHBASE_showMap_deviceEvents = function() {

        document.addEventListener("deviceready", function() {

        });
    }

    // screen elements extra js
    screen_B551_elementsExtraJS = CRUNCHBASE_showMap_elementsExtraJS = function() {
        // screen (CRUNCHBASE_showMap) extra code

        /* googlemap_officeLocation */

        $("[name = 'googlemap_officeLocation']").wrap("<div/>");
        $("[name = 'googlemap_officeLocation']").parent().css("margin-left", $("[name = 'googlemap_officeLocation']").css("margin-left"));
        $("[name = 'googlemap_officeLocation']").parent().css("margin-right", $("[name = 'googlemap_officeLocation']").css("margin-right"));
        $("[name = 'googlemap_officeLocation']").css("margin-left", '0');
        $("[name = 'googlemap_officeLocation']").css("margin-right", '0');

        var googlemap_officeLocation_options = {
            markerSourceName: "googlemap_officeLocation_markers",
            latitude: "",
            longitude: "",
            address: "",
            zoom: 10,
            showLocationMarker: true
        }

        Appery.__registerComponent('googlemap_officeLocation', new Appery.ApperyMapComponent("googlemap_officeLocation", googlemap_officeLocation_options));
        $("[name='googlemap_officeLocation_markers'] [apperytype='marker']").attr("reRender", "googlemap_officeLocation");
        $("[name='googlemap_officeLocation']").closest("[data-role='page']").bind({
            pageshow: function() {
                if (Appery('googlemap_officeLocation') != undefined) {
                    Appery('googlemap_officeLocation').refresh();
                }
            }
        });

    }

    // screen elements handler
    screen_B551_elementsEvents = CRUNCHBASE_showMap_elementsEvents = function() {

        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });

    }

    $("#CRUNCHBASE_showMap").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        CRUNCHBASE_showMap_beforeshow();
    });

    if (runBeforeShow) {
        CRUNCHBASE_showMap_beforeshow();
    } else {
        CRUNCHBASE_showMap_onLoad();
    }

}

$("#CRUNCHBASE_showMap").die("pageinit").live("pageinit", function(event, ui) {
    Appery.processSelectMenu($(this));
    CRUNCHBASE_showMap_js();
});