/*
 * JS for CRUNCHBASE_milestonesList generated by Appery.io
 *
 */

Appery.getProjectGUID = function() {
    return '10159332-6ca9-4e3e-8d2b-7b3a2ee01b02';
}

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Appery.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Appery.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "CRUNCHBASE_search",
    "location": "CRUNCHBASE_search.html"
}, {
    "name": "CRUNCHBASE_financialOrgInfo",
    "location": "CRUNCHBASE_financialOrgInfo.html"
}, {
    "name": "CRUNCHBASE_milestonesList",
    "location": "CRUNCHBASE_milestonesList.html"
}, {
    "name": "CRUNCHBASE_peopleList",
    "location": "CRUNCHBASE_peopleList.html"
}, {
    "name": "CRUNCHBASE_serviceProviderInfo",
    "location": "CRUNCHBASE_serviceProviderInfo.html"
}, {
    "name": "CRUNCHBASE_officesList",
    "location": "CRUNCHBASE_officesList.html"
}, {
    "name": "CRUNCHBASE_showMap",
    "location": "CRUNCHBASE_showMap.html"
}, {
    "name": "CRUNCHBASE_competitorsList",
    "location": "CRUNCHBASE_competitorsList.html"
}, {
    "name": "CRUNCHBASE_personInfo",
    "location": "CRUNCHBASE_personInfo.html"
}, {
    "name": "CRUNCHBASE_productsList",
    "location": "CRUNCHBASE_productsList.html"
}, {
    "name": "CRUNCHBASE_productInfo",
    "location": "CRUNCHBASE_productInfo.html"
}, {
    "name": "CRUNCHBASE_companyInfo",
    "location": "CRUNCHBASE_companyInfo.html"
}];

CRUNCHBASE_milestonesList_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_home': 'CRUNCHBASE_milestonesList_mobilebutton_home',
        'mobilebutton_back': 'CRUNCHBASE_milestonesList_mobilebutton_back',
        'mobilegrid_nameAndImage': 'CRUNCHBASE_milestonesList_mobilegrid_nameAndImage',
        'mobilegridcell_name': 'CRUNCHBASE_milestonesList_mobilegridcell_name',
        'mobilelink_companyName': 'CRUNCHBASE_milestonesList_mobilelink_companyName',
        'mobilegridcell_image': 'CRUNCHBASE_milestonesList_mobilegridcell_image',
        'mobileimage_company': 'CRUNCHBASE_milestonesList_mobileimage_company',
        'mobilelabel_category': 'CRUNCHBASE_milestonesList_mobilelabel_category',
        'mobilelabel_descriptionCompany': 'CRUNCHBASE_milestonesList_mobilelabel_descriptionCompany',
        'mobilegroupedbuttons_companyInfo': 'CRUNCHBASE_milestonesList_mobilegroupedbuttons_companyInfo',
        'mobilebutton_Overview': 'CRUNCHBASE_milestonesList_mobilebutton_Overview',
        'mobilebutton_Offices': 'CRUNCHBASE_milestonesList_mobilebutton_Offices',
        'mobilebutton_People': 'CRUNCHBASE_milestonesList_mobilebutton_People',
        'mobilebutton_Products': 'CRUNCHBASE_milestonesList_mobilebutton_Products',
        'mobilebutton_Competitors': 'CRUNCHBASE_milestonesList_mobilebutton_Competitors',
        'mobilebutton_Milestones': 'CRUNCHBASE_milestonesList_mobilebutton_Milestones',
        'mobilelabel_milestones': 'CRUNCHBASE_milestonesList_mobilelabel_milestones',
        'mobilelabel_noInformationMilestones': 'CRUNCHBASE_milestonesList_mobilelabel_noInformationMilestones',
        'mobilelist_milestones': 'CRUNCHBASE_milestonesList_mobilelist_milestones',
        'mobilelistitem_milestones': 'CRUNCHBASE_milestonesList_mobilelistitem_milestones',
        'mobilelabel_stonedYear': 'CRUNCHBASE_milestonesList_mobilelabel_stonedYear',
        'mobilelabel_stonedMonth': 'CRUNCHBASE_milestonesList_mobilelabel_stonedMonth',
        'mobilelabel_stonedDay': 'CRUNCHBASE_milestonesList_mobilelabel_stonedDay',
        'mobilelabel_stonedDescription': 'CRUNCHBASE_milestonesList_mobilelabel_stonedDescription',
        'mobilelink_stonedURL': 'CRUNCHBASE_milestonesList_mobilelink_stonedURL',
        'mobilelistitembutton_7': 'CRUNCHBASE_milestonesList_mobilelistitembutton_7'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=page] div[data-role=footer]").css("bottom", "-36px");
    }

    if (Appery.getTargetPlatform == "I") {
        $.each(window.n2id, function(name, id) {
            var elApperyRole = $("#" + id).attr("data-role");
            if (elApperyRole != "appery_label" && elApperyRole != "appery_link") {
                var appleDataSelector = "#" + id + "[x-apple-data-detectors], #" + id + " [x-apple-data-detectors]";
                $(appleDataSelector).attr("x-apple-data-detectors", "false");
            }
        });
    }

    Appery.CurrentScreen = 'CRUNCHBASE_milestonesList';

    /*
     * Nonvisual components
     */
    var datasources = [];

    getCompanyMilestones = new Appery.DataSource(CRUNCHBASE_getCompany, {
        'onComplete': function(jqXHR, textStatus) {

            $t.refreshScreenFormElements("CRUNCHBASE_milestonesList");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [{
            'PATH': ['image', 'available_sizes', '[0]', '.'],
            'ID': 'mobileimage_company',
            'ATTR': 'src',
            'TRANSFORMATION': function(value, element) {
                return Helper.getImage(value, element);
            }
        }, {
            'PATH': ['milestones'],
            'ID': 'mobilelistitem_milestones',
            'TRANSFORMATION': function(value, element) {
                Helper.setMilestonesListItemVisibility(value, element);
            },
            'SET': [{
                'PATH': ['description'],
                'ID': 'mobilelabel_stonedDescription',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    Helper.setElementVisibility(value, element);
                    Helper.setNoInformationVisibility(value, 'mobilelabel_noInformationMilestones');
                }
            }, {
                'PATH': ['stoned_year'],
                'ID': 'mobilelabel_stonedYear',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    Helper.setNoInformationVisibility(value, 'mobilelabel_noInformationMilestones');
                }
            }, {
                'PATH': ['stoned_month'],
                'ID': 'mobilelabel_stonedMonth',
                'ATTR': '@'
            }, {
                'PATH': ['stoned_day'],
                'ID': 'mobilelabel_stonedDay',
                'ATTR': '@'
            }, {
                'PATH': ['source_url'],
                'ID': 'mobilelink_stonedURL',
                'ATTR': 'href',
                'TRANSFORMATION': function(value, element) {
                    Helper.setElementVisibility(value, element);
                    Helper.setNoInformationVisibility(value, 'mobilelabel_noInformationMilestones');
                }
            }]
        }, {
            'PATH': ['name'],
            'ID': 'mobilelink_companyName',
            'ATTR': '@'
        }, {
            'PATH': ['homepage_url'],
            'ID': 'mobilelink_companyName',
            'ATTR': 'href'
        }, {
            'PATH': ['category_code'],
            'ID': 'mobilelabel_category',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                Helper.setElementVisibility(value, element);
                return Helper.getNewValue(value, 'Category: ');
            }
        }, {
            'PATH': ['description'],
            'ID': 'mobilelabel_descriptionCompany',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                Helper.setElementVisibility(value, element);
            }
        }],
        'requestMapping': [{
            'PATH': ['api_key'],
            'TYPE': 'STRING',
            'ATTR': '{api_key}'
        }, {
            'PATH': ['query'],
            'TYPE': 'STRING',
            'ID': '___local_storage___',
            'ATTR': 'selectedPermalink'
        }, {
            'PATH': ['appery-proxy-url'],
            'HEADER': true,
            'ATTR': 'http://api.crunchbase.com/v/1/company/{query}.js'
        }, {
            'PATH': ['appery-transformation'],
            'HEADER': true,
            'ATTR': 'checkTunnel'
        }, {
            'PATH': ['appery-key'],
            'HEADER': true,
            'ATTR': '1390718928526'
        }, {
            'PATH': ['appery-rest'],
            'HEADER': true,
            'ATTR': '2585836'
        }]
    });

    datasources.push(getCompanyMilestones);

    /*
     * Events and handlers
     */

    // Before Show
    CRUNCHBASE_milestonesList_beforeshow = function() {
        Appery.CurrentScreen = "CRUNCHBASE_milestonesList";
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }

    // On Load
    screen_2CA9_onLoad = CRUNCHBASE_milestonesList_onLoad = function() {
        screen_2CA9_elementsExtraJS();
        getCompanyMilestones.updateComponents(Helper.getJsonObject());

        Helper.setDateLabelsInList('mobilelist_milestones', 'mobilelabel_stonedDay', 'mobilelabel_stonedMonth', 'mobilelabel_stonedYear', 'Date: ');

        // TODO fire device events only if necessary (with JS logic)
        CRUNCHBASE_milestonesList_deviceEvents();
        CRUNCHBASE_milestonesList_windowEvents();
        screen_2CA9_elementsEvents();
    }

    // screen window events
    screen_2CA9_windowEvents = CRUNCHBASE_milestonesList_windowEvents = function() {

        $('#CRUNCHBASE_milestonesList').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    }

    // device events
    CRUNCHBASE_milestonesList_deviceEvents = function() {

        document.addEventListener("deviceready", function() {

        });
    }

    // screen elements extra js
    screen_2CA9_elementsExtraJS = CRUNCHBASE_milestonesList_elementsExtraJS = function() {
        // screen (CRUNCHBASE_milestonesList) extra code

        /* mobilelist_milestones */

        listView = $("#CRUNCHBASE_milestonesList_mobilelist_milestones");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#CRUNCHBASE_milestonesList_mobilelist_milestones .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_milestones */

    }

    // screen elements handler
    screen_2CA9_elementsEvents = CRUNCHBASE_milestonesList_elementsEvents = function() {

        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });

        $('#CRUNCHBASE_milestonesList_mobileheader [name="mobilebutton_home"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.goHome();

                }
            },
        });
        $('#CRUNCHBASE_milestonesList_mobileheader [name="mobilebutton_back"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.goBack('CRUNCHBASE_milestonesList');

                }
            },
        });

        $('#CRUNCHBASE_milestonesList_mobilecontainer [name="mobilebutton_Overview"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.navigateToNextListPage('CRUNCHBASE_companyInfo');;

                }
            },
        });
        $('#CRUNCHBASE_milestonesList_mobilecontainer [name="mobilebutton_Offices"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.navigateToNextListPage('CRUNCHBASE_officesList');;

                }
            },
        });
        $('#CRUNCHBASE_milestonesList_mobilecontainer [name="mobilebutton_People"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.navigateToNextListPage('CRUNCHBASE_peopleList');;

                }
            },
        });
        $('#CRUNCHBASE_milestonesList_mobilecontainer [name="mobilebutton_Products"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.navigateToNextListPage('CRUNCHBASE_productsList');;

                }
            },
        });
        $('#CRUNCHBASE_milestonesList_mobilecontainer [name="mobilebutton_Competitors"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.navigateToNextListPage('CRUNCHBASE_competitorsList');;

                }
            },
        });
        $('#CRUNCHBASE_milestonesList_mobilecontainer [name="mobilebutton_Milestones"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.navigateToNextListPage('CRUNCHBASE_milestonesList');

                }
            },
        });

    }

    $("#CRUNCHBASE_milestonesList").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        CRUNCHBASE_milestonesList_beforeshow();
    });

    if (runBeforeShow) {
        CRUNCHBASE_milestonesList_beforeshow();
    } else {
        CRUNCHBASE_milestonesList_onLoad();
    }

}

$("#CRUNCHBASE_milestonesList").die("pageinit").live("pageinit", function(event, ui) {
    Appery.processSelectMenu($(this));
    CRUNCHBASE_milestonesList_js();
});