/*
 * JS for CRUNCHBASE_financialOrgInfo generated by Appery.io
 *
 */

Appery.getProjectGUID = function() {
    return '10159332-6ca9-4e3e-8d2b-7b3a2ee01b02';
}

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Appery.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Appery.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "CRUNCHBASE_search",
    "location": "CRUNCHBASE_search.html"
}, {
    "name": "CRUNCHBASE_financialOrgInfo",
    "location": "CRUNCHBASE_financialOrgInfo.html"
}, {
    "name": "CRUNCHBASE_milestonesList",
    "location": "CRUNCHBASE_milestonesList.html"
}, {
    "name": "CRUNCHBASE_peopleList",
    "location": "CRUNCHBASE_peopleList.html"
}, {
    "name": "CRUNCHBASE_serviceProviderInfo",
    "location": "CRUNCHBASE_serviceProviderInfo.html"
}, {
    "name": "CRUNCHBASE_officesList",
    "location": "CRUNCHBASE_officesList.html"
}, {
    "name": "CRUNCHBASE_showMap",
    "location": "CRUNCHBASE_showMap.html"
}, {
    "name": "CRUNCHBASE_competitorsList",
    "location": "CRUNCHBASE_competitorsList.html"
}, {
    "name": "CRUNCHBASE_personInfo",
    "location": "CRUNCHBASE_personInfo.html"
}, {
    "name": "CRUNCHBASE_productsList",
    "location": "CRUNCHBASE_productsList.html"
}, {
    "name": "CRUNCHBASE_productInfo",
    "location": "CRUNCHBASE_productInfo.html"
}, {
    "name": "CRUNCHBASE_companyInfo",
    "location": "CRUNCHBASE_companyInfo.html"
}];

CRUNCHBASE_financialOrgInfo_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_back': 'CRUNCHBASE_financialOrgInfo_mobilebutton_back',
        'mobilebutton_home': 'CRUNCHBASE_financialOrgInfo_mobilebutton_home',
        'mobilegrid_NameAndImage': 'CRUNCHBASE_financialOrgInfo_mobilegrid_NameAndImage',
        'mobilegridcell_Name': 'CRUNCHBASE_financialOrgInfo_mobilegridcell_Name',
        'mobilelink_name': 'CRUNCHBASE_financialOrgInfo_mobilelink_name',
        'mobilegridcell_Imade': 'CRUNCHBASE_financialOrgInfo_mobilegridcell_Imade',
        'mobileimage_financial': 'CRUNCHBASE_financialOrgInfo_mobileimage_financial',
        'mobilelabel_descriptionFinancialOrg': 'CRUNCHBASE_financialOrgInfo_mobilelabel_descriptionFinancialOrg',
        'mobilecollapsibleset_organizationInfo': 'CRUNCHBASE_financialOrgInfo_mobilecollapsibleset_organizationInfo',
        'mobilecollapsblock_overview': 'CRUNCHBASE_financialOrgInfo_mobilecollapsblock_overview',
        'mobilecollapsblockheader_overview': 'CRUNCHBASE_financialOrgInfo_mobilecollapsblockheader_overview',
        'mobilecollapsblockcontent_overview': 'CRUNCHBASE_financialOrgInfo_mobilecollapsblockcontent_overview',
        'mobilelabel_overviewText': 'CRUNCHBASE_financialOrgInfo_mobilelabel_overviewText',
        'mobilelabel_noInformationOverview': 'CRUNCHBASE_financialOrgInfo_mobilelabel_noInformationOverview',
        'mobilelabel_foundedDayFO': 'CRUNCHBASE_financialOrgInfo_mobilelabel_foundedDayFO',
        'mobilelabel_foundedMonthFO': 'CRUNCHBASE_financialOrgInfo_mobilelabel_foundedMonthFO',
        'mobilelabel_foundedYearFO': 'CRUNCHBASE_financialOrgInfo_mobilelabel_foundedYearFO',
        'mobilelabel_numberOfEmployees': 'CRUNCHBASE_financialOrgInfo_mobilelabel_numberOfEmployees',
        'mobilelabel_overview': 'CRUNCHBASE_financialOrgInfo_mobilelabel_overview',
        'mobilelabel_contactsText': 'CRUNCHBASE_financialOrgInfo_mobilelabel_contactsText',
        'mobilelabel_noInformationContacts': 'CRUNCHBASE_financialOrgInfo_mobilelabel_noInformationContacts',
        'mobilelabel_phoneNumberText': 'CRUNCHBASE_financialOrgInfo_mobilelabel_phoneNumberText',
        'mobilelabel_phone': 'CRUNCHBASE_financialOrgInfo_mobilelabel_phone',
        'mobilelabel_emailText': 'CRUNCHBASE_financialOrgInfo_mobilelabel_emailText',
        'mobilelabel_email': 'CRUNCHBASE_financialOrgInfo_mobilelabel_email',
        'mobilelink_twitter': 'CRUNCHBASE_financialOrgInfo_mobilelink_twitter',
        'mobilelink_blog': 'CRUNCHBASE_financialOrgInfo_mobilelink_blog',
        'mobilecollapsblock_offices': 'CRUNCHBASE_financialOrgInfo_mobilecollapsblock_offices',
        'mobilecollapsblockheader_offices': 'CRUNCHBASE_financialOrgInfo_mobilecollapsblockheader_offices',
        'mobilecollapsblockcontent_offices': 'CRUNCHBASE_financialOrgInfo_mobilecollapsblockcontent_offices',
        'mobilelabel_noInformationOffices': 'CRUNCHBASE_financialOrgInfo_mobilelabel_noInformationOffices',
        'mobilelist_offices': 'CRUNCHBASE_financialOrgInfo_mobilelist_offices',
        'mobilelistitem_offices': 'CRUNCHBASE_financialOrgInfo_mobilelistitem_offices',
        'mobilelistitembutton_44': 'CRUNCHBASE_financialOrgInfo_mobilelistitembutton_44',
        'mobilelabel_description': 'CRUNCHBASE_financialOrgInfo_mobilelabel_description',
        'mobilelabel_city': 'CRUNCHBASE_financialOrgInfo_mobilelabel_city',
        'mobilelabel_addressesText': 'CRUNCHBASE_financialOrgInfo_mobilelabel_addressesText',
        'mobilelabel_address1': 'CRUNCHBASE_financialOrgInfo_mobilelabel_address1',
        'mobilelabel_address2': 'CRUNCHBASE_financialOrgInfo_mobilelabel_address2',
        'mobilelabel_zipCode': 'CRUNCHBASE_financialOrgInfo_mobilelabel_zipCode',
        'mobilelabel_countryCode': 'CRUNCHBASE_financialOrgInfo_mobilelabel_countryCode',
        'mobilelabel_stateCode': 'CRUNCHBASE_financialOrgInfo_mobilelabel_stateCode',
        'mobilelabel_latitude': 'CRUNCHBASE_financialOrgInfo_mobilelabel_latitude',
        'mobilelabel_longitude': 'CRUNCHBASE_financialOrgInfo_mobilelabel_longitude',
        'mobilecollapsblock_people': 'CRUNCHBASE_financialOrgInfo_mobilecollapsblock_people',
        'mobilecollapsblockheader_people': 'CRUNCHBASE_financialOrgInfo_mobilecollapsblockheader_people',
        'mobilecollapsblockcontent_people': 'CRUNCHBASE_financialOrgInfo_mobilecollapsblockcontent_people',
        'mobilelabel_noInformationPeople': 'CRUNCHBASE_financialOrgInfo_mobilelabel_noInformationPeople',
        'mobilelist_people': 'CRUNCHBASE_financialOrgInfo_mobilelist_people',
        'mobilelistitem_person': 'CRUNCHBASE_financialOrgInfo_mobilelistitem_person',
        'mobilelistitembutton_70': 'CRUNCHBASE_financialOrgInfo_mobilelistitembutton_70',
        'mobilelabel_title': 'CRUNCHBASE_financialOrgInfo_mobilelabel_title',
        'mobilelabel_isPast': 'CRUNCHBASE_financialOrgInfo_mobilelabel_isPast',
        'mobilelabel_firstName': 'CRUNCHBASE_financialOrgInfo_mobilelabel_firstName',
        'mobilelabel_lastName': 'CRUNCHBASE_financialOrgInfo_mobilelabel_lastName',
        'mobilelabel_personPermalink': 'CRUNCHBASE_financialOrgInfo_mobilelabel_personPermalink',
        'mobilecollapsblock_investments': 'CRUNCHBASE_financialOrgInfo_mobilecollapsblock_investments',
        'mobilecollapsblockheader_investments': 'CRUNCHBASE_financialOrgInfo_mobilecollapsblockheader_investments',
        'mobilecollapsblockcontent_investments': 'CRUNCHBASE_financialOrgInfo_mobilecollapsblockcontent_investments',
        'mobilelabel_noInformationInvestments': 'CRUNCHBASE_financialOrgInfo_mobilelabel_noInformationInvestments',
        'mobilelist_investments': 'CRUNCHBASE_financialOrgInfo_mobilelist_investments',
        'mobilelistitem_funding_round': 'CRUNCHBASE_financialOrgInfo_mobilelistitem_funding_round',
        'mobilelistitembutton_73': 'CRUNCHBASE_financialOrgInfo_mobilelistitembutton_73',
        'mobilelabel_company': 'CRUNCHBASE_financialOrgInfo_mobilelabel_company',
        'mobilelabel_sourceDescription': 'CRUNCHBASE_financialOrgInfo_mobilelabel_sourceDescription',
        'mobilelabel_roundCode': 'CRUNCHBASE_financialOrgInfo_mobilelabel_roundCode',
        'mobilelabel_raisedAmount': 'CRUNCHBASE_financialOrgInfo_mobilelabel_raisedAmount',
        'mobilelabel_raisedCurrencyCode': 'CRUNCHBASE_financialOrgInfo_mobilelabel_raisedCurrencyCode',
        'mobilelabel_fundedDay': 'CRUNCHBASE_financialOrgInfo_mobilelabel_fundedDay',
        'mobilelabel_fundedMonth': 'CRUNCHBASE_financialOrgInfo_mobilelabel_fundedMonth',
        'mobilelabel_fundedYear': 'CRUNCHBASE_financialOrgInfo_mobilelabel_fundedYear',
        'mobilelabel_companyPermalink': 'CRUNCHBASE_financialOrgInfo_mobilelabel_companyPermalink',
        'mobilelabel_loadingText': 'CRUNCHBASE_financialOrgInfo_mobilelabel_loadingText',
        'mobilebutton_retry': 'CRUNCHBASE_financialOrgInfo_mobilebutton_retry'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=page] div[data-role=footer]").css("bottom", "-36px");
    }

    if (Appery.getTargetPlatform == "I") {
        $.each(window.n2id, function(name, id) {
            var elApperyRole = $("#" + id).attr("data-role");
            if (elApperyRole != "appery_label" && elApperyRole != "appery_link") {
                var appleDataSelector = "#" + id + "[x-apple-data-detectors], #" + id + " [x-apple-data-detectors]";
                $(appleDataSelector).attr("x-apple-data-detectors", "false");
            }
        });
    }

    Appery.CurrentScreen = 'CRUNCHBASE_financialOrgInfo';

    /*
     * Nonvisual components
     */
    var datasources = [];

    getFinancialOrgInfo = new Appery.DataSource(CRUNCHBASE_getFinancialOrg, {
        'onComplete': function(jqXHR, textStatus) {

            $t.refreshScreenFormElements("CRUNCHBASE_financialOrgInfo");
        },
        'onSuccess': function(data) {
            Helper.setLoadingFinancialOrgSuccessState();
        },
        'onError': function(jqXHR, textStatus, errorThrown) {
            Helper.setLoadingFailedState('mobilebutton_retry', 'mobilelabel_loadingText');
        },
        'responseMapping': [{
            'PATH': ['image', 'available_sizes', '[0]', '.'],
            'ID': 'mobileimage_financial',
            'ATTR': 'src',
            'TRANSFORMATION': function(value, element) {
                return Helper.getImage(value, element);
            }
        }, {
            'PATH': ['offices'],
            'ID': 'mobilelistitem_offices',
            'SET': [{
                'PATH': ['description'],
                'ID': 'mobilelabel_description',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    Helper.setElementVisibility(value, element);
                    Helper.setNoInformationVisibility(value, 'mobilelabel_noInformationOffices');
                }
            }, {
                'PATH': ['address1'],
                'ID': 'mobilelabel_address1',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    Helper.setElementAndTextVisibility(value, element, 'mobilelabel_addressesText');
                    Helper.setNoInformationVisibility(value, 'mobilelabel_noInformationOffices');
                }
            }, {
                'PATH': ['address2'],
                'ID': 'mobilelabel_address2',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    Helper.setElementVisibility(value, element);
                }
            }, {
                'PATH': ['zip_code'],
                'ID': 'mobilelabel_zipCode',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    Helper.setElementVisibility(value, element);
                    Helper.setNoInformationVisibility(value, 'mobilelabel_noInformationOffices');
                    return Helper.getNewValue(value, "Zip code: ");
                }
            }, {
                'PATH': ['city'],
                'ID': 'mobilelabel_city',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    Helper.setElementVisibility(value, element);
                    Helper.setNoInformationVisibility(value, 'mobilelabel_noInformationOffices');
                    return Helper.getNewValue(value, "City: ");
                }
            }, {
                'PATH': ['state_code'],
                'ID': 'mobilelabel_stateCode',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    Helper.setElementVisibility(value, element);
                    Helper.setNoInformationVisibility(value, 'mobilelabel_noInformationOffices');
                    return Helper.getNewValue(value, "State code: ");
                }
            }, {
                'PATH': ['country_code'],
                'ID': 'mobilelabel_countryCode',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    Helper.setElementVisibility(value, element);
                    Helper.setNoInformationVisibility(value, 'mobilelabel_noInformationOffices');
                    return Helper.getNewValue(value, "Country code: ");
                }
            }, {
                'PATH': ['latitude'],
                'ID': 'mobilelabel_latitude',
                'ATTR': '@'
            }, {
                'PATH': ['longitude'],
                'ID': 'mobilelabel_longitude',
                'ATTR': '@'
            }]
        }, {
            'PATH': ['relationships'],
            'ID': 'mobilelistitem_person',
            'SET': [{
                'PATH': ['person', 'first_name'],
                'ID': 'mobilelabel_firstName',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    Helper.setNoInformationVisibility(value, 'mobilelabel_noInformationPeople');
                }
            }, {
                'PATH': ['person', 'last_name'],
                'ID': 'mobilelabel_lastName',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    Helper.setNoInformationVisibility(value, 'mobilelabel_noInformationPeople');
                }
            }, {
                'PATH': ['person', 'permalink'],
                'ID': 'mobilelabel_personPermalink',
                'ATTR': '@'
            }, {
                'PATH': ['is_past'],
                'ID': 'mobilelabel_isPast',
                'ATTR': 'visible'
            }, {
                'PATH': ['title'],
                'ID': 'mobilelabel_title',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    Helper.setNoInformationVisibility(value, 'mobilelabel_noInformationPeople');
                }
            }]
        }, {
            'PATH': ['investments'],
            'ID': 'mobilelistitem_funding_round',
            'SET': [{
                'PATH': ['funding_round', 'company', 'name'],
                'ID': 'mobilelabel_company',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    Helper.setNoInformationVisibility(value, 'mobilelabel_noInformationInvestments');
                }
            }, {
                'PATH': ['funding_round', 'company', 'permalink'],
                'ID': 'mobilelabel_companyPermalink',
                'ATTR': '@'
            }, {
                'PATH': ['funding_round', 'round_code'],
                'ID': 'mobilelabel_roundCode',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    Helper.setElementVisibility(value, element);
                    return Helper.getNewValue(value, 'Round code: ');
                }
            }, {
                'PATH': ['funding_round', 'source_description'],
                'ID': 'mobilelabel_sourceDescription',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    Helper.setElementVisibility(value, element);
                    Helper.setNoInformationVisibility(value, 'mobilelabel_noInformationInvestments');
                }
            }, {
                'PATH': ['funding_round', 'raised_amount'],
                'ID': 'mobilelabel_raisedAmount',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    Helper.setElementVisibility(value, element);
                    return Helper.getNewValue(value, "Raised amount: ");
                }
            }, {
                'PATH': ['funding_round', 'raised_currency_code'],
                'ID': 'mobilelabel_raisedCurrencyCode',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    Helper.setElementVisibility(value, element);
                    return Helper.getNewValue(value, "Currency: ");
                }
            }, {
                'PATH': ['funding_round', 'funded_year'],
                'ID': 'mobilelabel_fundedYear',
                'ATTR': '@'
            }, {
                'PATH': ['funding_round', 'funded_month'],
                'ID': 'mobilelabel_fundedMonth',
                'ATTR': '@'
            }, {
                'PATH': ['funding_round', 'funded_day'],
                'ID': 'mobilelabel_fundedDay',
                'ATTR': '@'
            }]
        }, {
            'PATH': ['name'],
            'ID': 'mobilelink_name',
            'ATTR': '@'
        }, {
            'PATH': ['homepage_url'],
            'ID': 'mobilelink_name',
            'ATTR': 'href'
        }, {
            'PATH': ['blog_url'],
            'ID': 'mobilelink_blog',
            'ATTR': 'href',
            'TRANSFORMATION': function(value, element) {
                Helper.setElementVisibility(value, element);
                Helper.setNoInformationState(value, 'mobilelabel_noInformationContacts');
            }
        }, {
            'PATH': ['twitter_username'],
            'ID': 'mobilelink_twitter',
            'ATTR': 'href',
            'TRANSFORMATION': function(value, element) {
                Helper.setElementVisibility(value, element);
                Helper.setNoInformationState(value, 'mobilelabel_noInformationContacts');
                return Helper.getNewValue(value, "http://twitter.com/");

            }
        }, {
            'PATH': ['phone_number'],
            'ID': 'mobilelabel_phone',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                Helper.setElementAndTextVisibility(value, element, 'mobilelabel_phoneNumberText');
                Helper.setNoInformationState(value, 'mobilelabel_noInformationContacts');
            }
        }, {
            'PATH': ['description'],
            'ID': 'mobilelabel_descriptionFinancialOrg',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                Helper.setElementVisibility(value, element);
            }
        }, {
            'PATH': ['email_address'],
            'ID': 'mobilelabel_email',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                Helper.setElementAndTextVisibility(value, element, 'mobilelabel_emailText');
                Helper.setNoInformationState(value, 'mobilelabel_noInformationContacts');
            }
        }, {
            'PATH': ['number_of_employees'],
            'ID': 'mobilelabel_numberOfEmployees',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                Helper.setElementVisibility(value, element);
                Helper.setNoInformationState(value, 'mobilelabel_noInformationOverview');
                return Helper.getNewValue(value, "Number of employees: ");
            }
        }, {
            'PATH': ['founded_year'],
            'ID': 'mobilelabel_foundedYearFO',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                Helper.setNoInformationState(value, 'mobilelabel_noInformationOverview');
            }
        }, {
            'PATH': ['founded_month'],
            'ID': 'mobilelabel_foundedMonthFO',
            'ATTR': '@'
        }, {
            'PATH': ['founded_day'],
            'ID': 'mobilelabel_foundedDayFO',
            'ATTR': '@'
        }, {
            'PATH': ['overview'],
            'ID': 'mobilelabel_overview',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                Helper.setElementVisibility(value, element);
                Helper.setNoInformationState(value, 'mobilelabel_noInformationOverview');
            }
        }],
        'requestMapping': [{
            'PATH': ['api_key'],
            'TYPE': 'STRING',
            'ATTR': '{api_key}'
        }, {
            'PATH': ['query'],
            'TYPE': 'STRING',
            'ID': '___local_storage___',
            'ATTR': 'selectedPermalink'
        }, {
            'PATH': ['appery-proxy-url'],
            'HEADER': true,
            'ATTR': 'http://api.crunchbase.com/v/1/financial-organization/{query}.js'
        }, {
            'PATH': ['appery-transformation'],
            'HEADER': true,
            'ATTR': 'checkTunnel'
        }, {
            'PATH': ['appery-key'],
            'HEADER': true,
            'ATTR': '1390718928680'
        }, {
            'PATH': ['appery-rest'],
            'HEADER': true,
            'ATTR': '2585829'
        }]
    });

    datasources.push(getFinancialOrgInfo);

    /*
     * Events and handlers
     */

    // Before Show
    CRUNCHBASE_financialOrgInfo_beforeshow = function() {
        Appery.CurrentScreen = "CRUNCHBASE_financialOrgInfo";
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }

    // On Load
    screen_3DA6_onLoad = CRUNCHBASE_financialOrgInfo_onLoad = function() {
        screen_3DA6_elementsExtraJS();
        Helper.setFinancialOrgInfoInvisibility();
        Helper.setLoadingState('mobilebutton_retry', 'mobilelabel_loadingText');
        getFinancialOrgInfo.execute({});
        localStorage.setItem('currentEntity', 'financial-organization');

        // TODO fire device events only if necessary (with JS logic)
        CRUNCHBASE_financialOrgInfo_deviceEvents();
        CRUNCHBASE_financialOrgInfo_windowEvents();
        screen_3DA6_elementsEvents();
    }

    // screen window events
    screen_3DA6_windowEvents = CRUNCHBASE_financialOrgInfo_windowEvents = function() {

        $('#CRUNCHBASE_financialOrgInfo').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    }

    // device events
    CRUNCHBASE_financialOrgInfo_deviceEvents = function() {

        document.addEventListener("deviceready", function() {

        });
    }

    // screen elements extra js
    screen_3DA6_elementsExtraJS = CRUNCHBASE_financialOrgInfo_elementsExtraJS = function() {
        // screen (CRUNCHBASE_financialOrgInfo) extra code

        /* mobilecollapsblock_overview */

        $("#CRUNCHBASE_financialOrgInfo_mobilecollapsblock_overview .ui-collapsible-heading-toggle").attr("tabindex", "1");

        /* mobilecollapsblock_offices */

        $("#CRUNCHBASE_financialOrgInfo_mobilecollapsblock_offices .ui-collapsible-heading-toggle").attr("tabindex", "3");

        /* mobilelist_offices */

        listView = $("#CRUNCHBASE_financialOrgInfo_mobilelist_offices");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#CRUNCHBASE_financialOrgInfo_mobilelist_offices .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_offices */

        /* mobilecollapsblock_people */

        $("#CRUNCHBASE_financialOrgInfo_mobilecollapsblock_people .ui-collapsible-heading-toggle").attr("tabindex", "5");

        /* mobilelist_people */

        listView = $("#CRUNCHBASE_financialOrgInfo_mobilelist_people");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#CRUNCHBASE_financialOrgInfo_mobilelist_people .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_person */

        /* mobilecollapsblock_investments */

        $("#CRUNCHBASE_financialOrgInfo_mobilecollapsblock_investments .ui-collapsible-heading-toggle").attr("tabindex", "7");

        /* mobilelist_investments */

        listView = $("#CRUNCHBASE_financialOrgInfo_mobilelist_investments");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#CRUNCHBASE_financialOrgInfo_mobilelist_investments .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_funding_round */

    }

    // screen elements handler
    screen_3DA6_elementsEvents = CRUNCHBASE_financialOrgInfo_elementsEvents = function() {

        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });

        $('#CRUNCHBASE_financialOrgInfo_mobileheader [name="mobilebutton_back"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.goBack('CRUNCHBASE_financialOrgInfo');

                }
            },
        });
        $('#CRUNCHBASE_financialOrgInfo_mobileheader [name="mobilebutton_home"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.goHome();

                }
            },
        });

        $('#CRUNCHBASE_financialOrgInfo_mobilecontainer [name="mobilelistitem_offices"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    setVar_('current_longitude', 'CRUNCHBASE_financialOrgInfo_mobilelabel_longitude', 'text', '', this);
                    setVar_('current_latitude', 'CRUNCHBASE_financialOrgInfo_mobilelabel_latitude', 'text', '', this);
                    Appery.navigateTo('CRUNCHBASE_showMap', {
                        transition: 'slide',
                        reverse: false
                    });

                }
            },
        });

        $('#CRUNCHBASE_financialOrgInfo_mobilecontainer [name="mobilelistitem_person"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Pages.push('CRUNCHBASE_financialOrgInfo', localStorage.getItem('selectedPermalink'));
                    setVar_('selectedPermalink', 'CRUNCHBASE_financialOrgInfo_mobilelabel_personPermalink', 'text', '', this);
                    Helper.navigateToNextPage('person', 'CRUNCHBASE_financialOrgInfo');

                }
            },
        });

        $('#CRUNCHBASE_financialOrgInfo_mobilecontainer [name="mobilelistitem_funding_round"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Pages.push('CRUNCHBASE_financialOrgInfo', localStorage.getItem('selectedPermalink'));
                    setVar_('selectedPermalink', 'CRUNCHBASE_financialOrgInfo_mobilelabel_companyPermalink', 'text', '', this);
                    Helper.navigateToNextPage('company', 'CRUNCHBASE_financialOrgInfo');

                }
            },
        });

        $('#CRUNCHBASE_financialOrgInfo_mobilecontainer [name="mobilebutton_retry"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.setLoadingState('mobilebutton_retry', 'mobilelabel_loadingText');
                    getFinancialOrgInfo.execute({});

                }
            },
        });

    }

    $("#CRUNCHBASE_financialOrgInfo").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        CRUNCHBASE_financialOrgInfo_beforeshow();
    });

    if (runBeforeShow) {
        CRUNCHBASE_financialOrgInfo_beforeshow();
    } else {
        CRUNCHBASE_financialOrgInfo_onLoad();
    }

}

$("#CRUNCHBASE_financialOrgInfo").die("pageinit").live("pageinit", function(event, ui) {
    Appery.processSelectMenu($(this));
    CRUNCHBASE_financialOrgInfo_js();
});