/*
 * JS for CRUNCHBASE_officesList generated by Appery.io
 *
 */

Appery.getProjectGUID = function() {
    return '10159332-6ca9-4e3e-8d2b-7b3a2ee01b02';
}

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Appery.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Appery.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "CRUNCHBASE_search",
    "location": "CRUNCHBASE_search.html"
}, {
    "name": "CRUNCHBASE_financialOrgInfo",
    "location": "CRUNCHBASE_financialOrgInfo.html"
}, {
    "name": "CRUNCHBASE_milestonesList",
    "location": "CRUNCHBASE_milestonesList.html"
}, {
    "name": "CRUNCHBASE_peopleList",
    "location": "CRUNCHBASE_peopleList.html"
}, {
    "name": "CRUNCHBASE_serviceProviderInfo",
    "location": "CRUNCHBASE_serviceProviderInfo.html"
}, {
    "name": "CRUNCHBASE_officesList",
    "location": "CRUNCHBASE_officesList.html"
}, {
    "name": "CRUNCHBASE_showMap",
    "location": "CRUNCHBASE_showMap.html"
}, {
    "name": "CRUNCHBASE_competitorsList",
    "location": "CRUNCHBASE_competitorsList.html"
}, {
    "name": "CRUNCHBASE_personInfo",
    "location": "CRUNCHBASE_personInfo.html"
}, {
    "name": "CRUNCHBASE_productsList",
    "location": "CRUNCHBASE_productsList.html"
}, {
    "name": "CRUNCHBASE_productInfo",
    "location": "CRUNCHBASE_productInfo.html"
}, {
    "name": "CRUNCHBASE_companyInfo",
    "location": "CRUNCHBASE_companyInfo.html"
}];

CRUNCHBASE_officesList_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_home': 'CRUNCHBASE_officesList_mobilebutton_home',
        'mobilebutton_back': 'CRUNCHBASE_officesList_mobilebutton_back',
        'mobilegrid_nameAndImage': 'CRUNCHBASE_officesList_mobilegrid_nameAndImage',
        'mobilegridcell_name': 'CRUNCHBASE_officesList_mobilegridcell_name',
        'mobilelink_companyName': 'CRUNCHBASE_officesList_mobilelink_companyName',
        'mobilegridcell_image': 'CRUNCHBASE_officesList_mobilegridcell_image',
        'mobileimage_company': 'CRUNCHBASE_officesList_mobileimage_company',
        'mobilelabel_category': 'CRUNCHBASE_officesList_mobilelabel_category',
        'mobilelabel_descriptionCompany': 'CRUNCHBASE_officesList_mobilelabel_descriptionCompany',
        'mobilegroupedbuttons_companyInfo': 'CRUNCHBASE_officesList_mobilegroupedbuttons_companyInfo',
        'mobilebutton_Overview': 'CRUNCHBASE_officesList_mobilebutton_Overview',
        'mobilebutton_Offices': 'CRUNCHBASE_officesList_mobilebutton_Offices',
        'mobilebutton_People': 'CRUNCHBASE_officesList_mobilebutton_People',
        'mobilebutton_Products': 'CRUNCHBASE_officesList_mobilebutton_Products',
        'mobilebutton_Competitors': 'CRUNCHBASE_officesList_mobilebutton_Competitors',
        'mobilebutton_Milestones': 'CRUNCHBASE_officesList_mobilebutton_Milestones',
        'mobilelabel_officesText': 'CRUNCHBASE_officesList_mobilelabel_officesText',
        'mobilelabel_noInformationOffices': 'CRUNCHBASE_officesList_mobilelabel_noInformationOffices',
        'mobilelist_office': 'CRUNCHBASE_officesList_mobilelist_office',
        'mobilelistitem_offices': 'CRUNCHBASE_officesList_mobilelistitem_offices',
        'mobilelistitembutton_10': 'CRUNCHBASE_officesList_mobilelistitembutton_10',
        'mobilelabel_descriptionOffice': 'CRUNCHBASE_officesList_mobilelabel_descriptionOffice',
        'mobilelabel_city': 'CRUNCHBASE_officesList_mobilelabel_city',
        'mobilelabel_addressesText': 'CRUNCHBASE_officesList_mobilelabel_addressesText',
        'mobilelabel_address1': 'CRUNCHBASE_officesList_mobilelabel_address1',
        'mobilelabel_address2': 'CRUNCHBASE_officesList_mobilelabel_address2',
        'mobilelabel_zipCode': 'CRUNCHBASE_officesList_mobilelabel_zipCode',
        'mobilelabel_countryCode': 'CRUNCHBASE_officesList_mobilelabel_countryCode',
        'mobilelabel_stateCode': 'CRUNCHBASE_officesList_mobilelabel_stateCode',
        'mobilelabel_latitude': 'CRUNCHBASE_officesList_mobilelabel_latitude',
        'mobilelabel_longitude': 'CRUNCHBASE_officesList_mobilelabel_longitude'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=page] div[data-role=footer]").css("bottom", "-36px");
    }

    if (Appery.getTargetPlatform == "I") {
        $.each(window.n2id, function(name, id) {
            var elApperyRole = $("#" + id).attr("data-role");
            if (elApperyRole != "appery_label" && elApperyRole != "appery_link") {
                var appleDataSelector = "#" + id + "[x-apple-data-detectors], #" + id + " [x-apple-data-detectors]";
                $(appleDataSelector).attr("x-apple-data-detectors", "false");
            }
        });
    }

    Appery.CurrentScreen = 'CRUNCHBASE_officesList';

    /*
     * Nonvisual components
     */
    var datasources = [];

    getCompanyOffices = new Appery.DataSource(CRUNCHBASE_getCompany, {
        'onComplete': function(jqXHR, textStatus) {

            $t.refreshScreenFormElements("CRUNCHBASE_officesList");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [{
            'PATH': ['image', 'available_sizes', '[0]', '.'],
            'ID': 'mobileimage_company',
            'ATTR': 'src',
            'TRANSFORMATION': function(value, element) {
                return Helper.getImage(value, element);
            }
        }, {
            'PATH': ['offices'],
            'ID': 'mobilelistitem_offices',
            'TRANSFORMATION': function(value, element) {
                Helper.setOfficeListItemVisibility(value, element);
            },
            'SET': [{
                'PATH': ['description'],
                'ID': 'mobilelabel_descriptionOffice',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    Helper.setElementVisibility(value, element);
                    Helper.setNoInformationVisibility(value, 'mobilelabel_noInformationOffices');
                }
            }, {
                'PATH': ['address1'],
                'ID': 'mobilelabel_address1',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    Helper.setElementAndTextVisibility(value, element, 'mobilelabel_addressesText');
                    Helper.setNoInformationVisibility(value, 'mobilelabel_noInformationOffices');
                }
            }, {
                'PATH': ['address2'],
                'ID': 'mobilelabel_address2',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    Helper.setElementVisibility(value, element);
                    Helper.setNoInformationVisibility(value, 'mobilelabel_noInformationOffices');
                }
            }, {
                'PATH': ['zip_code'],
                'ID': 'mobilelabel_zipCode',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    Helper.setElementVisibility(value, element);
                    Helper.setNoInformationVisibility(value, 'mobilelabel_noInformationOffices');
                    return Helper.getNewValue(value, "Zip code: ");
                }
            }, {
                'PATH': ['city'],
                'ID': 'mobilelabel_city',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    Helper.setElementVisibility(value, element);
                    Helper.setNoInformationVisibility(value, 'mobilelabel_noInformationOffices');
                    return Helper.getNewValue(value, "City: ");
                }
            }, {
                'PATH': ['state_code'],
                'ID': 'mobilelabel_stateCode',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    Helper.setElementVisibility(value, element);
                    Helper.setNoInformationVisibility(value, 'mobilelabel_noInformationOffices');
                    return Helper.getNewValue(value, "State code: ");
                }
            }, {
                'PATH': ['country_code'],
                'ID': 'mobilelabel_countryCode',
                'ATTR': '@',
                'TRANSFORMATION': function(value, element) {
                    Helper.setElementVisibility(value, element);
                    Helper.setNoInformationVisibility(value, 'mobilelabel_noInformationOffices');
                    return Helper.getNewValue(value, "Country code: ");
                }
            }, {
                'PATH': ['latitude'],
                'ID': 'mobilelabel_latitude',
                'ATTR': '@'
            }, {
                'PATH': ['longitude'],
                'ID': 'mobilelabel_longitude',
                'ATTR': '@'
            }]
        }, {
            'PATH': ['name'],
            'ID': 'mobilelink_companyName',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                Helper.setElementVisibility(value, element);
            }
        }, {
            'PATH': ['homepage_url'],
            'ID': 'mobilelink_companyName',
            'ATTR': 'href'
        }, {
            'PATH': ['category_code'],
            'ID': 'mobilelabel_category',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                Helper.setElementVisibility(value, element);
                return Helper.getNewValue(value, 'Category: ');
            }
        }, {
            'PATH': ['description'],
            'ID': 'mobilelabel_descriptionCompany',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                Helper.setElementVisibility(value, element);
            }
        }],
        'requestMapping': [{
            'PATH': ['api_key'],
            'TYPE': 'STRING',
            'ATTR': '{api_key}'
        }, {
            'PATH': ['query'],
            'TYPE': 'STRING',
            'ID': '___local_storage___',
            'ATTR': 'selectedPermalink'
        }, {
            'PATH': ['appery-proxy-url'],
            'HEADER': true,
            'ATTR': 'http://api.crunchbase.com/v/1/company/{query}.js'
        }, {
            'PATH': ['appery-transformation'],
            'HEADER': true,
            'ATTR': 'checkTunnel'
        }, {
            'PATH': ['appery-key'],
            'HEADER': true,
            'ATTR': '1390718928915'
        }, {
            'PATH': ['appery-rest'],
            'HEADER': true,
            'ATTR': '2585836'
        }]
    });

    datasources.push(getCompanyOffices);

    /*
     * Events and handlers
     */

    // Before Show
    CRUNCHBASE_officesList_beforeshow = function() {
        Appery.CurrentScreen = "CRUNCHBASE_officesList";
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }

    // On Load
    screen_F631_onLoad = CRUNCHBASE_officesList_onLoad = function() {
        screen_F631_elementsExtraJS();
        getCompanyOffices.updateComponents(Helper.getJsonObject());

        // TODO fire device events only if necessary (with JS logic)
        CRUNCHBASE_officesList_deviceEvents();
        CRUNCHBASE_officesList_windowEvents();
        screen_F631_elementsEvents();
    }

    // screen window events
    screen_F631_windowEvents = CRUNCHBASE_officesList_windowEvents = function() {

        $('#CRUNCHBASE_officesList').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    }

    // device events
    CRUNCHBASE_officesList_deviceEvents = function() {

        document.addEventListener("deviceready", function() {

        });
    }

    // screen elements extra js
    screen_F631_elementsExtraJS = CRUNCHBASE_officesList_elementsExtraJS = function() {
        // screen (CRUNCHBASE_officesList) extra code

        /* mobilelist_office */

        listView = $("#CRUNCHBASE_officesList_mobilelist_office");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#CRUNCHBASE_officesList_mobilelist_office .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }

        /* mobilelistitem_offices */

    }

    // screen elements handler
    screen_F631_elementsEvents = CRUNCHBASE_officesList_elementsEvents = function() {

        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });

        $('#CRUNCHBASE_officesList_mobileheader [name="mobilebutton_home"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.goHome();

                }
            },
        });
        $('#CRUNCHBASE_officesList_mobileheader [name="mobilebutton_back"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.goBack('CRUNCHBASE_officesList');

                }
            },
        });

        $('#CRUNCHBASE_officesList_mobilecontainer [name="mobilebutton_Overview"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.navigateToNextListPage('CRUNCHBASE_companyInfo');;

                }
            },
        });
        $('#CRUNCHBASE_officesList_mobilecontainer [name="mobilebutton_Offices"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.navigateToNextListPage('CRUNCHBASE_officesList');;

                }
            },
        });
        $('#CRUNCHBASE_officesList_mobilecontainer [name="mobilebutton_People"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.navigateToNextListPage('CRUNCHBASE_peopleList');;

                }
            },
        });
        $('#CRUNCHBASE_officesList_mobilecontainer [name="mobilebutton_Products"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.navigateToNextListPage('CRUNCHBASE_productsList');;

                }
            },
        });
        $('#CRUNCHBASE_officesList_mobilecontainer [name="mobilebutton_Competitors"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.navigateToNextListPage('CRUNCHBASE_competitorsList');;

                }
            },
        });
        $('#CRUNCHBASE_officesList_mobilecontainer [name="mobilebutton_Milestones"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.navigateToNextListPage('CRUNCHBASE_milestonesList');

                }
            },
        });

        $('#CRUNCHBASE_officesList_mobilecontainer [name="mobilelistitem_offices"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    setVar_('current_longitude', 'CRUNCHBASE_officesList_mobilelabel_longitude', 'text', '', this);
                    setVar_('current_latitude', 'CRUNCHBASE_officesList_mobilelabel_latitude', 'text', '', this);
                    Appery.navigateTo('CRUNCHBASE_showMap', {
                        reverse: false
                    });

                }
            },
        });

    }

    $("#CRUNCHBASE_officesList").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        CRUNCHBASE_officesList_beforeshow();
    });

    if (runBeforeShow) {
        CRUNCHBASE_officesList_beforeshow();
    } else {
        CRUNCHBASE_officesList_onLoad();
    }

}

$("#CRUNCHBASE_officesList").die("pageinit").live("pageinit", function(event, ui) {
    Appery.processSelectMenu($(this));
    CRUNCHBASE_officesList_js();
});