/*
 * JS for CRUNCHBASE_productInfo generated by Appery.io
 *
 */

Appery.getProjectGUID = function() {
    return '10159332-6ca9-4e3e-8d2b-7b3a2ee01b02';
}

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Appery.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Appery.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "CRUNCHBASE_search",
    "location": "CRUNCHBASE_search.html"
}, {
    "name": "CRUNCHBASE_financialOrgInfo",
    "location": "CRUNCHBASE_financialOrgInfo.html"
}, {
    "name": "CRUNCHBASE_milestonesList",
    "location": "CRUNCHBASE_milestonesList.html"
}, {
    "name": "CRUNCHBASE_peopleList",
    "location": "CRUNCHBASE_peopleList.html"
}, {
    "name": "CRUNCHBASE_serviceProviderInfo",
    "location": "CRUNCHBASE_serviceProviderInfo.html"
}, {
    "name": "CRUNCHBASE_officesList",
    "location": "CRUNCHBASE_officesList.html"
}, {
    "name": "CRUNCHBASE_showMap",
    "location": "CRUNCHBASE_showMap.html"
}, {
    "name": "CRUNCHBASE_competitorsList",
    "location": "CRUNCHBASE_competitorsList.html"
}, {
    "name": "CRUNCHBASE_personInfo",
    "location": "CRUNCHBASE_personInfo.html"
}, {
    "name": "CRUNCHBASE_productsList",
    "location": "CRUNCHBASE_productsList.html"
}, {
    "name": "CRUNCHBASE_productInfo",
    "location": "CRUNCHBASE_productInfo.html"
}, {
    "name": "CRUNCHBASE_companyInfo",
    "location": "CRUNCHBASE_companyInfo.html"
}];

CRUNCHBASE_productInfo_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_back': 'CRUNCHBASE_productInfo_mobilebutton_back',
        'mobilebutton_home': 'CRUNCHBASE_productInfo_mobilebutton_home',
        'mobilegrid_nameAndImage': 'CRUNCHBASE_productInfo_mobilegrid_nameAndImage',
        'mobilegridcell_name': 'CRUNCHBASE_productInfo_mobilegridcell_name',
        'mobilelink_productName': 'CRUNCHBASE_productInfo_mobilelink_productName',
        'mobilegridcell_image': 'CRUNCHBASE_productInfo_mobilegridcell_image',
        'mobileimage_product': 'CRUNCHBASE_productInfo_mobileimage_product',
        'mobilelabel_overviewText': 'CRUNCHBASE_productInfo_mobilelabel_overviewText',
        'mobilelabel_noInformationOverview': 'CRUNCHBASE_productInfo_mobilelabel_noInformationOverview',
        'mobilelink_companyName': 'CRUNCHBASE_productInfo_mobilelink_companyName',
        'mobilelabel_launchedYear': 'CRUNCHBASE_productInfo_mobilelabel_launchedYear',
        'mobilelabel_deadpooledYear': 'CRUNCHBASE_productInfo_mobilelabel_deadpooledYear',
        'mobilelabel_deadpooledMonth': 'CRUNCHBASE_productInfo_mobilelabel_deadpooledMonth',
        'mobilelabel_deadpooledDay': 'CRUNCHBASE_productInfo_mobilelabel_deadpooledDay',
        'mobilelabel_launchedMonth': 'CRUNCHBASE_productInfo_mobilelabel_launchedMonth',
        'mobilelabel_launchedDay': 'CRUNCHBASE_productInfo_mobilelabel_launchedDay',
        'mobilelabel_overview': 'CRUNCHBASE_productInfo_mobilelabel_overview',
        'mobilelabel_companyPermalink': 'CRUNCHBASE_productInfo_mobilelabel_companyPermalink',
        'mobilelabel_contactsText': 'CRUNCHBASE_productInfo_mobilelabel_contactsText',
        'mobilelabel_noInformationContacts': 'CRUNCHBASE_productInfo_mobilelabel_noInformationContacts',
        'mobilelink_blog': 'CRUNCHBASE_productInfo_mobilelink_blog',
        'mobilelink_twitter': 'CRUNCHBASE_productInfo_mobilelink_twitter',
        'mobilelabel_loadingText': 'CRUNCHBASE_productInfo_mobilelabel_loadingText',
        'mobilebutton_retry': 'CRUNCHBASE_productInfo_mobilebutton_retry'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=page] div[data-role=footer]").css("bottom", "-36px");
    }

    if (Appery.getTargetPlatform == "I") {
        $.each(window.n2id, function(name, id) {
            var elApperyRole = $("#" + id).attr("data-role");
            if (elApperyRole != "appery_label" && elApperyRole != "appery_link") {
                var appleDataSelector = "#" + id + "[x-apple-data-detectors], #" + id + " [x-apple-data-detectors]";
                $(appleDataSelector).attr("x-apple-data-detectors", "false");
            }
        });
    }

    Appery.CurrentScreen = 'CRUNCHBASE_productInfo';

    /*
     * Nonvisual components
     */
    var datasources = [];

    getProductInfo = new Appery.DataSource(CRUNCHBASE_getProduct, {
        'onComplete': function(jqXHR, textStatus) {

            $t.refreshScreenFormElements("CRUNCHBASE_productInfo");
        },
        'onSuccess': function(data) {
            Helper.setLoadingProductSuccessState();
        },
        'onError': function(jqXHR, textStatus, errorThrown) {
            Helper.setLoadingFailedState('mobilebutton_retry', 'mobilelabel_loadingText');
        },
        'responseMapping': [{
            'PATH': ['image', 'available_sizes', '[0]', '.'],
            'ID': 'mobileimage_product',
            'ATTR': 'src',
            'TRANSFORMATION': function(value, element) {
                return Helper.getImage(value, element);
            }
        }, {
            'PATH': ['company', 'name'],
            'ID': 'mobilelink_companyName',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                element.attr('href', '#');
                Helper.setNoInformationState(value, 'mobilelabel_noInformationOverview');
                Helper.setElementVisibility(value, element);
                return Helper.getNewValue(value, "Company: ");
            }
        }, {
            'PATH': ['company', 'permalink'],
            'ID': 'mobilelabel_companyPermalink',
            'ATTR': '@'
        }, {
            'PATH': ['name'],
            'ID': 'mobilelink_productName',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                Helper.setElementVisibility(value, element);
            }
        }, {
            'PATH': ['homepage_url'],
            'ID': 'mobilelink_productName',
            'ATTR': 'href'
        }, {
            'PATH': ['blog_url'],
            'ID': 'mobilelink_blog',
            'ATTR': 'href',
            'TRANSFORMATION': function(value, element) {
                Helper.setElementVisibility(value, element);
                Helper.setNoInformationState(value, 'mobilelabel_noInformationContacts');
            }
        }, {
            'PATH': ['twitter_username'],
            'ID': 'mobilelink_twitter',
            'ATTR': 'href',
            'TRANSFORMATION': function(value, element) {
                Helper.setElementVisibility(value, element);
                Helper.setNoInformationState(value, 'mobilelabel_noInformationContacts');
                return Helper.getNewValue(value, "http://twitter.com/");
            }
        }, {
            'PATH': ['deadpooled_year'],
            'ID': 'mobilelabel_deadpooledYear',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                Helper.setNoInformationState(value, 'mobilelabel_noInformationOverview');
            }
        }, {
            'PATH': ['deadpooled_month'],
            'ID': 'mobilelabel_deadpooledMonth',
            'ATTR': '@'
        }, {
            'PATH': ['deadpooled_day'],
            'ID': 'mobilelabel_deadpooledDay',
            'ATTR': '@'
        }, {
            'PATH': ['launched_year'],
            'ID': 'mobilelabel_launchedYear',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                Helper.setNoInformationState(value, 'mobilelabel_noInformationOverview');
            }
        }, {
            'PATH': ['launched_month'],
            'ID': 'mobilelabel_launchedMonth',
            'ATTR': '@'
        }, {
            'PATH': ['launched_day'],
            'ID': 'mobilelabel_launchedDay',
            'ATTR': '@'
        }, {
            'PATH': ['overview'],
            'ID': 'mobilelabel_overview',
            'ATTR': '@',
            'TRANSFORMATION': function(value, element) {
                Helper.setElementVisibility(value, element);
                Helper.setNoInformationState(value, 'mobilelabel_noInformationOverview');
            }
        }],
        'requestMapping': [{
            'PATH': ['api_key'],
            'TYPE': 'STRING',
            'ATTR': '{api_key}'
        }, {
            'PATH': ['query'],
            'TYPE': 'STRING',
            'ID': '___local_storage___',
            'ATTR': 'selectedPermalink'
        }, {
            'PATH': ['appery-proxy-url'],
            'HEADER': true,
            'ATTR': 'http://api.crunchbase.com/v/1/product/{query}.js'
        }, {
            'PATH': ['appery-transformation'],
            'HEADER': true,
            'ATTR': 'checkTunnel'
        }, {
            'PATH': ['appery-key'],
            'HEADER': true,
            'ATTR': '1390718929404'
        }, {
            'PATH': ['appery-rest'],
            'HEADER': true,
            'ATTR': '2585838'
        }]
    });

    datasources.push(getProductInfo);

    /*
     * Events and handlers
     */

    // Before Show
    CRUNCHBASE_productInfo_beforeshow = function() {
        Appery.CurrentScreen = "CRUNCHBASE_productInfo";
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }

    // On Load
    screen_7612_onLoad = CRUNCHBASE_productInfo_onLoad = function() {
        screen_7612_elementsExtraJS();
        Helper.setProductInfoInvisibility();
        Helper.setLoadingState('mobilebutton_retry', 'mobilelabel_loadingText');
        getProductInfo.execute({});
        localStorage.setItem('currentEntity', 'product');

        // TODO fire device events only if necessary (with JS logic)
        CRUNCHBASE_productInfo_deviceEvents();
        CRUNCHBASE_productInfo_windowEvents();
        screen_7612_elementsEvents();
    }

    // screen window events
    screen_7612_windowEvents = CRUNCHBASE_productInfo_windowEvents = function() {

        $('#CRUNCHBASE_productInfo').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });

    }

    // device events
    CRUNCHBASE_productInfo_deviceEvents = function() {

        document.addEventListener("deviceready", function() {

        });
    }

    // screen elements extra js
    screen_7612_elementsExtraJS = CRUNCHBASE_productInfo_elementsExtraJS = function() {
        // screen (CRUNCHBASE_productInfo) extra code

    }

    // screen elements handler
    screen_7612_elementsEvents = CRUNCHBASE_productInfo_elementsEvents = function() {

        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });

        $('#CRUNCHBASE_productInfo_mobileheader [name="mobilebutton_back"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.goBack('CRUNCHBASE_productInfo');

                }
            },
        });
        $('#CRUNCHBASE_productInfo_mobileheader [name="mobilebutton_home"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.goHome();

                }
            },
        });

        $('#CRUNCHBASE_productInfo_mobilecontainer [name="mobilelink_companyName"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Pages.push('CRUNCHBASE_productInfo', localStorage.getItem('selectedPermalink'));
                    setVar_('selectedPermalink', 'CRUNCHBASE_productInfo_mobilelabel_companyPermalink', 'text', '', this);
                    Helper.navigateToNextPage('company', 'CRUNCHBASE_productInfo');

                }
            },
        });

        $('#CRUNCHBASE_productInfo_mobilecontainer [name="mobilebutton_retry"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Helper.setLoadingState('mobilebutton_retry', 'mobilelabel_loadingText');
                    getProductInfo.execute({});

                }
            },
        });

    }

    $("#CRUNCHBASE_productInfo").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        CRUNCHBASE_productInfo_beforeshow();
    });

    if (runBeforeShow) {
        CRUNCHBASE_productInfo_beforeshow();
    } else {
        CRUNCHBASE_productInfo_onLoad();
    }

}

$("#CRUNCHBASE_productInfo").die("pageinit").live("pageinit", function(event, ui) {
    Appery.processSelectMenu($(this));
    CRUNCHBASE_productInfo_js();
});